import React,{useState} from 'react';
import {ScrollView,Text,Alert,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {api} from '../lib/api';
import {Field,Button,Card,H1} from '../components/ui';
import {Select} from '../components/StudentDirectory';
import {STUDENT_CLASSES} from '../lib/studentClasses';
import DatePickerField from '../components/DatePickerField';
import PageNavigation from '../components/PageNavigation';

export default function Dues(){
 const [registration,setRegistration]=useState(''),[student,setStudent]=useState<any>(null),[summary,setSummary]=useState<any>(null),[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[dueDate,setDueDate]=useState(''),[bulkClass,setBulkClass]=useState('*'),[bulkTitle,setBulkTitle]=useState(''),[bulkAmount,setBulkAmount]=useState(''),[bulkDate,setBulkDate]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const reg=registration.trim();if(!reg)return Alert.alert('Required','Enter student registration number.');setBusy(true);try{const result=await api('/api/students?q='+encodeURIComponent(reg));const found=(result.students||[]).find((x:any)=>String(x.registration_no).toLowerCase()===reg.toLowerCase());if(!found)throw new Error('Student not found for this registration number.');const data=await api('/api/dues/student/'+found.id+'/summary');setStudent(data.student);setSummary(data);}catch(e:any){setStudent(null);setSummary(null);Alert.alert('Dues',e.message)}finally{setBusy(false)}};
 const add=async()=>{if(!student)return Alert.alert('Required','Load a student first.');try{await api('/api/dues',{method:'POST',body:JSON.stringify({student_id:student.id,due_title:title,amount:Number(amount),due_date:dueDate||null})});setTitle('');setAmount('');setDueDate('');await load();Alert.alert('Saved','Due added successfully.')}catch(e:any){Alert.alert('Error',e.message)}};
 const addBulk=async()=>{if(!bulkTitle.trim()||!Number(bulkAmount)||Number(bulkAmount)<=0)return Alert.alert('Required','Enter due title and a positive amount.');setBusy(true);try{const result=await api('/api/dues/bulk',{method:'POST',body:JSON.stringify({class_name:bulkClass,due_title:bulkTitle.trim(),amount:Number(bulkAmount),due_date:bulkDate||null})});setBulkTitle('');setBulkAmount('');setBulkDate('');Alert.alert('Saved',`${result.created} student dues added.`)}catch(e:any){Alert.alert('Bulk SDF Due',e.message)}finally{setBusy(false)}};
 return <SafeAreaView style={{flex:1,backgroundColor:'#f3f6f9'}}><ScrollView contentContainerStyle={{padding:16}}><PageNavigation/><H1>Student Dues</H1><Card><Text style={{fontSize:18,fontWeight:'900'}}>Bulk SDF Due Entry</Text><Text style={{color:'#52677d',marginBottom:8}}>Bus Fare, Admission Fee বা Registration Fee একই amount-এ নির্দিষ্ট class বা সব active student-এর জন্য যোগ করুন।</Text><Select label="Class" value={bulkClass} onChange={setBulkClass} options={[{value:'*',label:'All Classes'},...STUDENT_CLASSES.map(v=>({value:v,label:v}))]}/><Field placeholder="Due title (e.g. Bus Fare)" value={bulkTitle} onChangeText={setBulkTitle}/><Field placeholder="Amount" value={bulkAmount} onChangeText={setBulkAmount} keyboardType="numeric"/><DatePickerField label="Due Date" value={bulkDate} onChange={setBulkDate} optional/><Button title={busy?'Saving...':'Add Due for Selected Class'} onPress={addBulk}/></Card><Field placeholder="Student Registration Number" value={registration} onChangeText={setRegistration} keyboardType="numeric"/><Button title={busy?'Loading...':'View Monthly & SDF Due'} onPress={load}/>{student&&summary&&<><Card><Text style={{fontSize:18,fontWeight:'800'}}>{student.student_name}</Text><Text>Registration No: {student.registration_no}  |  Class: {student.class_name||'-'}</Text></Card><Text style={{fontSize:18,fontWeight:'800',marginTop:14,marginBottom:8}}>Monthly Fees Due</Text><Card>{summary.monthly_dues?.length?summary.monthly_dues.map((x:any)=><View key={x.id} style={{paddingVertical:7,borderBottomWidth:1,borderBottomColor:'#e2e8f0'}}><Text style={{fontWeight:'700'}}>{x.due_title}</Text><Text>Rs. {Number(x.amount||0).toFixed(2)}{x.due_date?'  |  '+String(x.due_date).slice(0,10):''}</Text></View>):<Text>No Monthly Fee Due</Text>}<Text style={{fontWeight:'900',fontSize:16,marginTop:10}}>Total Monthly Due: Rs. {Number(summary.monthly_due_total||0).toFixed(2)}</Text></Card><Text style={{fontSize:18,fontWeight:'800',marginTop:14,marginBottom:8}}>Student Deposit Fund (SDF)</Text><Card><Text style={{fontSize:20,fontWeight:'900',color:Number(summary.sdf_due||0)>0?'#b42318':'#16804a'}}>SDF Due: Rs. {Number(summary.sdf_due||0).toFixed(2)}</Text><Text>Fund Balance: Rs. {Number(summary.sdf_balance||0).toFixed(2)}</Text>{summary.sdf_dues?.map((x:any)=><Text key={x.id} style={{marginTop:6}}>{x.due_title}: Rs. {Number(x.amount||0).toFixed(2)}</Text>)}</Card><Text style={{fontSize:18,fontWeight:'800',marginTop:14,marginBottom:8}}>Add Due</Text><Field placeholder="Due title" value={title} onChangeText={setTitle}/><Field placeholder="Amount" value={amount} onChangeText={setAmount} keyboardType="numeric"/><DatePickerField label="Due Date" value={dueDate} onChange={setDueDate} optional/><Button title="Add Due" onPress={add}/></>}</ScrollView></SafeAreaView>;
}
