import React,{useMemo,useState}from'react';
import{Alert,Image,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{router}from'expo-router';
import*as Print from'expo-print';
import QRCode from'qrcode';
import AcademyHeader from'../components/AcademyHeader';
import{api,API_BASE}from'../lib/api';
const logoAsset=require('../../assets/images/al-ameen-logo.jpg');
const logoUri=()=>Image.resolveAssetSource?Image.resolveAssetSource(logoAsset).uri:'';
const types=[['student','Student'],['father','Father'],['mother','Mother'],['visitor1','Visitor-1'],['visitor2','Visitor-2']]as const;
const url=(v?:string)=>!v?'':/^https?:|^data:/i.test(v)?v:API_BASE+(v.startsWith('/')?v:'/'+v);
const txt=(v:any)=>String(v??'').trim(),safe=(v:any)=>txt(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const addr=(p:any,s:any)=>txt(p?.address)||[p?.village,p?.post_office,p?.police_station,p?.district,p?.state,p?.pin_code].filter(Boolean).join(', ')||txt(s.address);
type Card={key:string;label:string;name:string;relation:string;phone:string;address:string;photo:string};
export default function IdCards(){
 const[reg,setReg]=useState(''),[student,setStudent]=useState<any>(null),[photos,setPhotos]=useState<Record<string,string>>({}),[qr,setQr]=useState(''),[busy,setBusy]=useState(false),[session,setSession]=useState('2026-2027'),[visitDay,setVisitDay]=useState('As per approved permission'),[selected,setSelected]=useState<Record<string,boolean>>({student:true,father:true,mother:true,visitor1:true,visitor2:true});
 const cards=useMemo<Card[]>(()=>{if(!student)return[];const v1=student.visitor1||{},v2=student.visitor2||{},a=student.address||[student.village,student.post_office,student.police_station,student.district,student.state,student.pin_code].filter(Boolean).join(', ');return[
  {key:'student',label:'Student',name:student.student_name,relation:'Student',phone:student.guardian_mobile||student.mobile_number,address:a,photo:url(student.photo_url)},
  {key:'father',label:'Father',name:student.father_name,relation:'Father',phone:student.guardian_mobile||student.father_mobile,address:a,photo:url(photos.father_photo)},
  {key:'mother',label:'Mother',name:student.mother_name,relation:'Mother',phone:student.alternate_mobile||student.mother_mobile||student.guardian_mobile,address:a,photo:url(photos.mother_photo)},
  {key:'visitor1',label:'Visitor-1',name:v1.visitor_name,relation:v1.relation||'Visitor-1',phone:v1.mobile_number,address:addr(v1,student),photo:url(photos.visitor1_photo)},
  {key:'visitor2',label:'Visitor-2',name:v2.visitor_name,relation:v2.relation||'Visitor-2',phone:v2.mobile_number,address:addr(v2,student),photo:url(photos.visitor2_photo)}]},[student,photos]);
 const load=async()=>{const r=reg.trim();if(!r)return Alert.alert('Required','Enter registration number.');setBusy(true);try{const list=await api('/api/students?q='+encodeURIComponent(r)),match=(list.students||[]).find((x:any)=>txt(x.registration_no).toLowerCase()===r.toLowerCase());if(!match)throw new Error('Student not found');const[d,docs,code]=await Promise.all([api('/api/students/'+match.id),api('/api/documents/student/'+match.id),QRCode.toDataURL(txt(match.registration_no),{width:280,margin:1,errorCorrectionLevel:'M'})]);const map:Record<string,string>={};for(const x of docs.documents||[])if(!map[x.document_type])map[x.document_type]=x.file_url;setStudent(d.student);setPhotos(map);setQr(code)}catch(e:any){setStudent(null);Alert.alert('I-Card',e.message)}finally{setBusy(false)}};
 const htmlCard=(c:Card)=>{const sp=url(student.photo_url),hp=c.photo||(c.key==='student'?sp:'');return'<div class="card"><header><img src="'+safe(logoUri())+'"><div><b>Al-Ameen Mission Academy, Memari</b><span>Memari * Purba Bardhaman * 713146</span><small>(Run By: Al-Ameen Mission Trust, Khalatpur, Howrah)</small></div></header><main><div class="sp">'+(sp?'<img src="'+safe(sp)+'">':'No Photo')+'</div><div class="info">Name&nbsp;&nbsp;: '+safe(student.student_name)+'<br>Reg. No: '+safe(student.registration_no)+'<br>Class&nbsp;&nbsp;&nbsp;: '+safe(student.class_name)+' ('+safe(session)+')</div><aside><img class="qr" src="'+safe(qr)+'"><div class="hp">'+(hp?'<img src="'+safe(hp)+'">':'No Photo')+'</div></aside><div class="details">'+safe(c.relation)+'&nbsp;&nbsp;: '+safe(c.name||'-')+'<br>Phone&nbsp;&nbsp;&nbsp;: '+safe(c.phone||'-')+'<br>Address : '+safe(c.address||'-')+'<br>Visit Day: '+safe(visitDay||'-')+'</div><footer>Signature Of Incharge <span>Print On : '+new Date().toLocaleDateString('en-GB').replace(/\//g,'-')+'</span></footer></main></div>'};
 const print=async()=>{const chosen=cards.filter(c=>selected[c.key]&&c.name);if(!chosen.length)return Alert.alert('I-Card','Select at least one available card.');const css='@page{size:A4 landscape;margin:8mm}*{box-sizing:border-box}body{margin:0;font-family:Arial}.sheet{display:flex;flex-wrap:wrap;gap:6mm}.card{width:86mm;height:54mm;border:1px solid;border-radius:4mm;overflow:hidden;font-size:9pt}header{height:17mm;background:linear-gradient(90deg,#bed99e,#86cad7);display:flex;align-items:center;text-align:center;padding:1mm 3mm}header>img{width:13mm;height:13mm;object-fit:contain}header>div{flex:1}header b,header span,header small{display:block}header b{font-size:12pt}header small{font-size:7pt}main{height:37mm;position:relative}.sp,.hp{width:15mm;height:19mm;border:1px solid #ccd5df;border-radius:2mm;display:flex;align-items:center;justify-content:center;font-size:6pt;overflow:hidden}.sp{position:absolute;left:2mm;top:2mm}.sp img,.hp img{width:100%;height:100%;object-fit:cover}.info{position:absolute;left:20mm;top:2mm;line-height:5mm}aside{position:absolute;right:2mm;top:1mm}.qr{width:15mm;height:15mm;display:block}.hp{height:15mm;margin-top:1mm}.details{position:absolute;left:2mm;right:2mm;top:22mm;line-height:4mm;white-space:nowrap;overflow:hidden}footer{position:absolute;left:2mm;right:2mm;bottom:1mm;border-top:1px dashed;padding-top:1mm}footer span{float:right;font-size:7pt}';await Print.printAsync({html:'<html><head><meta charset="utf-8"><style>'+css+'</style></head><body><div class="sheet">'+chosen.map(htmlCard).join('')+'</div></body></html>'})};
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><AcademyHeader/><View style={s.top}><Text style={s.title}>Student & Guardian I-Card Print</Text><TouchableOpacity style={s.close} onPress={()=>router.back()}><Text style={s.white}>Close</Text></TouchableOpacity></View><View style={s.row}><TextInput style={s.input} value={reg} onChangeText={setReg} onSubmitEditing={load} placeholder="Registration Number"/><TouchableOpacity style={s.load} onPress={load}><Text style={s.white}>{busy?'Loading...':'Load Student'}</Text></TouchableOpacity></View>{student&&<><View style={s.options}>{types.map(([k,l])=><TouchableOpacity key={k} style={s.choice} onPress={()=>setSelected(x=>({...x,[k]:!x[k]}))}><Text style={s.check}>{selected[k]?'☑':'☐'}</Text><Text>{l}</Text></TouchableOpacity>)}</View><View style={s.row}><TextInput style={s.input} value={session} onChangeText={setSession} placeholder="Academic Session"/><TextInput style={s.input} value={visitDay} onChangeText={setVisitDay} placeholder="Visit Day"/><TouchableOpacity style={s.print} onPress={print}><Text style={s.white}>Print Selected Cards</Text></TouchableOpacity></View><Text style={s.heading}>{student.student_name} · Reg. {student.registration_no} · Class {student.class_name}</Text><View style={s.grid}>{cards.filter(c=>selected[c.key]).map(c=><Preview key={c.key} card={c} student={student} qr={qr} session={session} visitDay={visitDay}/>)}</View></>}</ScrollView></SafeAreaView>};
function Pic({uri,small}:any){return<View style={[s.pic,small&&s.picSmall]}>{uri?<Image source={{uri}} style={s.picImg}/>:<Text style={s.small}>No Photo</Text>}</View>}
function Preview({card,student,qr,session,visitDay}:any){return<View style={s.card}><View style={s.cardHead}><Image source={logoAsset} style={s.logo}/><View style={s.center}><Text style={s.academy}>Al-Ameen Mission Academy, Memari</Text><Text>Memari * Purba Bardhaman * 713146</Text><Text style={s.small}>(Run By: Al-Ameen Mission Trust, Khalatpur, Howrah)</Text></View></View><View style={s.cardBody}><View style={s.cardTop}><Pic uri={url(student.photo_url)}/><View style={s.info}><Text>Name : {student.student_name}</Text><Text>Reg. No: {student.registration_no}</Text><Text>Class : {student.class_name} ({session})</Text></View><View>{qr&&<Image source={{uri:qr}} style={s.qr}/>}<Pic uri={card.photo||(card.key==='student'?url(student.photo_url):'')} small/></View></View><Text>{card.relation} : {card.name||'-'}</Text><Text>Phone : {card.phone||'-'}</Text><Text numberOfLines={1}>Address : {card.address||'-'}</Text><Text numberOfLines={1}>Visit Day : {visitDay||'-'}</Text><View style={s.sign}><Text>Signature Of Incharge</Text><Text style={s.small}>Print On : {new Date().toLocaleDateString('en-GB').replace(/\//g,'-')}</Text></View></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#eef3fb'},content:{padding:18,gap:14},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:24,fontWeight:'800'},row:{flexDirection:'row',flexWrap:'wrap',gap:10},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#cbd5e1',borderRadius:7,paddingHorizontal:12,minHeight:44,minWidth:220,flex:1},load:{backgroundColor:'#1769d2',paddingHorizontal:18,justifyContent:'center',borderRadius:7},close:{backgroundColor:'#dc3545',padding:10,borderRadius:6},print:{backgroundColor:'#16834f',paddingHorizontal:18,justifyContent:'center',borderRadius:7},white:{color:'#fff',fontWeight:'700'},options:{flexDirection:'row',flexWrap:'wrap',gap:16,backgroundColor:'#fff',padding:14,borderRadius:8},choice:{flexDirection:'row',alignItems:'center',gap:5},check:{fontSize:21,color:'#1769d2'},heading:{fontSize:17,fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:18},card:{width:443,height:278,borderWidth:1,borderRadius:12,overflow:'hidden',backgroundColor:'#fff'},cardHead:{height:72,backgroundColor:'#a9d2bf',flexDirection:'row',alignItems:'center',paddingHorizontal:10},logo:{width:58,height:58,resizeMode:'contain'},center:{flex:1,alignItems:'center'},academy:{fontSize:18,fontWeight:'800'},small:{fontSize:9},cardBody:{flex:1,padding:7},cardTop:{flexDirection:'row',height:90},pic:{width:70,height:84,borderWidth:1,borderColor:'#cbd5e1',borderRadius:7,alignItems:'center',justifyContent:'center',overflow:'hidden'},picSmall:{width:58,height:58,marginTop:3},picImg:{width:'100%',height:'100%',resizeMode:'cover'},info:{flex:1,paddingHorizontal:10,gap:5},qr:{width:58,height:58},sign:{borderTopWidth:1,borderStyle:'dashed',marginTop:'auto',paddingTop:3,flexDirection:'row',justifyContent:'space-between'}});

