import React,{useState} from 'react';import {ScrollView,Text,Alert} from 'react-native';import {SafeAreaView} from 'react-native-safe-area-context';import * as Print from 'expo-print';import {api} from '../lib/api';import {Field,Button,Card,H1} from '../components/ui';
export default function Marks(){const [examName,setExamName]=useState(''),[className,setClassName]=useState(''),[examId,setExamId]=useState(''),[studentId,setStudentId]=useState(''),[subjectId,setSubjectId]=useState(''),[marks,setMarks]=useState(''),[pending,setPending]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]);
const createExam=async()=>{try{const d=await api('/api/marks/exams',{method:'POST',body:JSON.stringify({exam_name:examName,class_name:className})});setExamId(String(d.exam.id));Alert.alert('Created',`Exam ID: ${d.exam.id}`)}catch(e:any){Alert.alert('Error',e.message)}};
const entry=async()=>{try{await api('/api/marks/entry',{method:'POST',body:JSON.stringify({exam_id:Number(examId),student_id:Number(studentId),subject_id:Number(subjectId),obtained_marks:Number(marks)})});Alert.alert('Saved','Marks saved / pending verification');}catch(e:any){Alert.alert('Error',e.message)}};
const loadPending=async()=>{try{const d=await api('/api/marks/pending');setPending(d.marks)}catch(e:any){Alert.alert('Error',e.message)}};
const verify=async(id:number,status:string)=>{try{await api(`/api/marks/${id}/verify`,{method:'PATCH',body:JSON.stringify({status})});loadPending();}catch(e:any){Alert.alert('Error',e.message)}};
const loadList=async()=>{try{const d=await api(`/api/marks/exam/${examId}/class/${encodeURIComponent(className)}`);setRows(d.rows)}catch(e:any){Alert.alert('Error',e.message)}};
const print=async()=>{const html=`<h2>Marks List - ${className}</h2><table border="1" cellspacing="0" cellpadding="6"><tr><th>Student</th><th>Subject</th><th>Marks</th><th>Status</th></tr>${rows.map(r=>`<tr><td>${r.student_name}</td><td>${r.subject_name||''}</td><td>${r.obtained_marks??''}</td><td>${r.verification_status||''}</td></tr>`).join('')}</table>`;await Print.printAsync({html});};
return <SafeAreaView style={{flex:1,backgroundColor:'#f3f6f9'}}><ScrollView contentContainerStyle={{padding:16}}><H1>Marks & Result</H1><Field placeholder="Exam name" value={examName} onChangeText={setExamName}/><Field placeholder="Class" value={className} onChangeText={setClassName}/><Button title="Create Exam" onPress={createExam}/><Field placeholder="Exam ID" value={examId} onChangeText={setExamId} keyboardType="numeric"/><Field placeholder="Student ID" value={studentId} onChangeText={setStudentId} keyboardType="numeric"/><Field placeholder="Subject ID" value={subjectId} onChangeText={setSubjectId} keyboardType="numeric"/><Field placeholder="Obtained marks" value={marks} onChangeText={setMarks} keyboardType="numeric"/><Button title="Save Marks" onPress={entry}/><Button title="Load Pending Verification" onPress={loadPending}/>{pending.map(x=><Card key={x.id}><Text style={{fontWeight:'800'}}>{x.student_name} • {x.subject_name}</Text><Text>{x.obtained_marks} • entered by {x.entered_by_name||'-'}</Text><Button title="Verify" onPress={()=>verify(x.id,'verified')}/><Button title="Reject" danger onPress={()=>verify(x.id,'rejected')}/></Card>)}<Button title="Load Marks List" onPress={loadList}/>{rows.map((r,i)=><Card key={`${r.student_id}-${i}`}><Text>{r.student_name} • {r.subject_name||'-'} • {r.obtained_marks??'-'}</Text></Card>)}{rows.length>0&&<Button title="Print Marks List" onPress={print}/>}</ScrollView></SafeAreaView>}
