import React,{useEffect,useState}from'react';
import{Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import{router,useLocalSearchParams}from'expo-router';
import*as Print from'expo-print';
import{api}from'../lib/api';
import AcademyHeader from'../components/AcademyHeader';
import DatePickerField from'../components/DatePickerField';
import{Select}from'../components/StudentDirectory';
import{STUDENT_CLASSES}from'../lib/studentClasses';
const today=()=>new Date().toISOString().slice(0,10),session=()=>{const y=new Date().getFullYear();return`${y}-${y+1}`};
export default function Lifecycle(){const params=useLocalSearchParams();const[tab,setTab]=useState(String(params.tab||'promotion'));const[students,setStudents]=useState<any[]>([]),[selected,setSelected]=useState<number[]>([]),[fromClass,setFromClass]=useState(''),[toClass,setToClass]=useState(''),[fromSession,setFromSession]=useState(session()),[toSession,setToSession]=useState(()=>{const y=new Date().getFullYear()+1;return`${y}-${y+1}`}),[q,setQ]=useState(''),[busy,setBusy]=useState(false);const[inactive,setInactive]=useState<any[]>([]),[studentId,setStudentId]=useState(''),[reason,setReason]=useState(''),[requestDate,setRequestDate]=useState(today()),[requests,setRequests]=useState<any[]>([]),[clearance,setClearance]=useState<any>(null);
 const loadPromotion=async()=>{try{const p=new URLSearchParams({active:'true',class_name:fromClass,session:fromSession,q});const d=await api('/api/student-lifecycle/students?'+p);setStudents(d.students||[]);setSelected([])}catch(e:any){Alert.alert('Promotion',e.message)}};
 const loadInactive=async()=>{try{const d=await api('/api/student-lifecycle/students?active=false&q='+encodeURIComponent(q));const rows=d.students||[];setInactive(rows);const r=await api('/api/student-lifecycle/reactivations');setRequests(r.requests||[]);if(tab==='tc'&&rows.length===1){const id=String(rows[0].id);setStudentId(id);try{setClearance(await api('/api/students/'+id+'/exit-clearance'))}catch{setClearance(null)}}}catch(e:any){Alert.alert('Students',e.message)}};
 useEffect(()=>{if(tab!=='promotion')void loadInactive()},[tab]);
 const promote=async()=>{if(!selected.length)return Alert.alert('Select students','Select at least one student.');setBusy(true);try{const d=await api('/api/student-lifecycle/promotions/bulk',{method:'POST',body:JSON.stringify({student_ids:selected,from_session:fromSession,to_session:toSession,to_class:toClass})});Alert.alert('Promotion complete',`${d.promoted} students promoted.`);await loadPromotion()}catch(e:any){Alert.alert('Promotion',e.message)}finally{setBusy(false)}};
 const checkTc=async(id=studentId)=>{if(!id)return;try{const d=await api('/api/students/'+id+'/exit-clearance');setClearance(d)}catch(e:any){Alert.alert('TC',e.message)}};
 const printTc=async()=>{if(!studentId)return;setBusy(true);try{const d=await api('/api/students/'+studentId+'/transfer-certificate',{method:'POST'}),st=d.student,ex=d.exit,fees=Number(d.monthly_fee_due_total||0),sess=[st.session_from,st.session_to].filter(Boolean).join('-');const esc=(x:any)=>String(x??'-').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));const html=`<style>@page{size:A4;margin:18mm}body{font:15px Georgia;color:#111}.sheet{border:2px solid #174c36;padding:28px;min-height:245mm}header{text-align:center;border-bottom:2px solid #174c36;padding-bottom:14px}h1{font-size:24px}h2{text-align:center;text-decoration:underline;margin:30px}.row{display:grid;grid-template-columns:190px 1fr;border-bottom:1px dotted #777;padding:10px}.note{margin-top:24px;padding:12px;border:1px solid #999}.sign{display:flex;justify-content:space-between;margin-top:70px}</style><div class="sheet"><header><h1>Al-Ameen Mission Academy Memari</h1><div>Memari, Purba Bardhaman - 713146</div></header><h2>TRANSFER CERTIFICATE</h2><div class="row"><b>Student Name</b><span>${esc(st.student_name)}</span></div><div class="row"><b>Registration No.</b><span>${esc(st.registration_no)}</span></div><div class="row"><b>Class</b><span>${esc(st.class_name)}</span></div><div class="row"><b>Academic Session</b><span>${esc(sess)}</span></div><div class="row"><b>Guardian</b><span>${esc(st.guardian_name||st.father_name)}</span></div><div class="row"><b>Dropout Date</b><span>${esc(String(ex.dropout_date).slice(0,10))}</span></div><div class="row"><b>Reason</b><span>${esc(ex.dropout_reason)}</span></div><div class="note"><b>Monthly Fees Due:</b> ${fees?'Rs. '+fees.toFixed(2):'No due'}${fees?'<br>The outstanding monthly fees remain payable.':''}</div><div class="sign"><span>Prepared By</span><span>Guardian</span><span>Principal / Administrator</span></div></div>`;await Print.printAsync({html});await loadInactive()}catch(e:any){Alert.alert('TC cannot be issued',e.message)}finally{setBusy(false)}};
 const request=async()=>{if(!studentId)return Alert.alert('Required','Select a dropout student.');setBusy(true);try{await api('/api/student-lifecycle/reactivations',{method:'POST',body:JSON.stringify({student_id:Number(studentId),reason,request_date:requestDate})});setReason('');setStudentId('');await loadInactive();Alert.alert('Saved','Re-activation request submitted for approval.')}catch(e:any){Alert.alert('Re-Activation',e.message)}finally{setBusy(false)}};
 const review=async(id:number,action:string)=>{try{await api(`/api/student-lifecycle/reactivations/${id}/${action}`,{method:'PATCH',body:'{}'});await loadInactive()}catch(e:any){Alert.alert('Re-Activation',e.message)}};
 const pick=(id:number)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const studentOptions=[{value:'',label:'Select dropout student'},...inactive.map(x=>({value:String(x.id),label:`${x.registration_no} - ${x.student_name} (${x.class_name||'-'})`}))];
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.body}><AcademyHeader/><View style={s.nav}><TouchableOpacity style={s.light} onPress={()=>router.back()}><Text>Back</Text></TouchableOpacity><TouchableOpacity style={s.light} onPress={()=>router.push('/superadmin')}><Text>Home</Text></TouchableOpacity></View><Text style={s.title}>Student Session Lifecycle</Text><View style={s.tabs}>{[['promotion','Bulk Promotion'],['tc','Transfer Certificate'],['reactivation','Re-Activation']].map(([k,l])=><TouchableOpacity key={k} style={[s.tab,tab===k&&s.active]} onPress={()=>{setTab(k);setStudentId('');setClearance(null)}}><Text style={tab===k?s.white:s.bold}>{l}</Text></TouchableOpacity>)}</View>
 {tab==='promotion'&&<View style={s.card}><Text style={s.heading}>Session-end Bulk Promotion</Text><View style={s.grid}><Select label="From class" value={fromClass} onChange={setFromClass} options={[{value:'',label:'Select current class'},...STUDENT_CLASSES.map(v=>({value:v,label:v}))]}/><Field label="From session" value={fromSession} onChange={setFromSession}/><Select label="Promote to" value={toClass} onChange={setToClass} options={[{value:'',label:'Select next class'},...STUDENT_CLASSES.map(v=>({value:v,label:v})),{value:'Passed Out',label:'Passed Out (deactivate)'}]}/><Field label="New session" value={toSession} onChange={setToSession}/><Field label="Search" value={q} onChange={setQ}/><TouchableOpacity style={s.light} onPress={loadPromotion}><Text>Load Students</Text></TouchableOpacity></View><View style={s.actions}><TouchableOpacity style={s.light} onPress={()=>setSelected(selected.length===students.length?[]:students.map(x=>x.id))}><Text>{selected.length===students.length?'Clear All':'Select All'}</Text></TouchableOpacity><Text>{selected.length} selected</Text><TouchableOpacity disabled={busy||!toClass} style={[s.primary,(busy||!toClass)&&s.disabled]} onPress={promote}><Text style={s.white}>{busy?'Promoting...':'Promote Selected Students'}</Text></TouchableOpacity></View><Table rows={students} selected={selected} onPick={pick}/></View>}
 {tab==='tc'&&<View style={s.card}><Text style={s.heading}>Transfer Certificate</Text><View style={s.grid}><Field label="Search dropout student" value={q} onChange={setQ}/><TouchableOpacity style={s.light} onPress={loadInactive}><Text>Search</Text></TouchableOpacity><Select label="Student" value={studentId} onChange={v=>{setStudentId(v);setClearance(null)}} options={studentOptions}/><TouchableOpacity style={s.light} onPress={()=>checkTc()}><Text>Check Clearance</Text></TouchableOpacity></View>{clearance&&<View style={s.notice}><Text style={clearance.sdf_dues?.length?s.red:s.green}>SDF: {clearance.sdf_dues?.length?'Due — TC blocked':'Clear'}</Text><Text style={clearance.library_dues?.length?s.red:s.green}>Library Book: {clearance.library_dues?.length?'Due — TC blocked':'Clear'}</Text><Text>Monthly Fees Due: Rs. {Number(clearance.monthly_fee_due_total||0).toFixed(2)} (printed on TC)</Text><Text>Dropout: {clearance.exit?String(clearance.exit.dropout_date).slice(0,10)+' — '+clearance.exit.dropout_reason:'Not recorded'}</Text></View>}<TouchableOpacity disabled={busy||!clearance?.exit||clearance?.tc_blocked} style={[s.primary,(busy||!clearance?.exit||clearance?.tc_blocked)&&s.disabled]} onPress={printTc}><Text style={s.white}>Issue / Print T.C.</Text></TouchableOpacity></View>}
 {tab==='reactivation'&&<View style={s.card}><Text style={s.heading}>Dropout Student Re-Activation</Text><View style={s.grid}><Field label="Search dropout student" value={q} onChange={setQ}/><TouchableOpacity style={s.light} onPress={loadInactive}><Text>Search</Text></TouchableOpacity><Select label="Student" value={studentId} onChange={setStudentId} options={studentOptions}/><DatePickerField label="Request date" value={requestDate} onChange={setRequestDate}/><Field label="Reason for re-activation" value={reason} onChange={setReason} multiline/></View><TouchableOpacity disabled={busy} style={s.primary} onPress={request}><Text style={s.white}>Submit Re-Activation Request</Text></TouchableOpacity><Text style={s.heading}>Approval Queue</Text>{requests.map(x=><View key={x.id} style={s.request}><View style={{flex:1}}><Text style={s.bold}>{x.registration_no} — {x.student_name}</Text><Text>{x.request_date} · {x.request_reason}</Text><Text>Status: {x.status}</Text></View>{x.status==='pending'&&<View style={s.actions}><TouchableOpacity style={s.ok} onPress={()=>review(x.id,'approve')}><Text style={s.white}>Approve</Text></TouchableOpacity><TouchableOpacity style={s.danger} onPress={()=>review(x.id,'reject')}><Text style={s.white}>Reject</Text></TouchableOpacity></View>}</View>)}</View>}
 </ScrollView></SafeAreaView>}
function Field({label,value,onChange,multiline=false}:any){return <View style={{minWidth:190,flex:1}}><Text style={s.bold}>{label}</Text><TextInput value={value} onChangeText={onChange} multiline={multiline} style={[s.input,multiline&&{minHeight:70}]}/></View>}
function Table({rows,selected,onPick}:any){return <ScrollView horizontal><View style={{minWidth:760}}>{rows.map((x:any)=><TouchableOpacity key={x.id} style={s.row} onPress={()=>onPick(x.id)}><Text style={s.check}>{selected.includes(x.id)?'☑':'☐'}</Text><Text style={s.cell}>{x.registration_no}</Text><Text style={[s.cell,{flex:2}]}>{x.student_name}</Text><Text style={s.cell}>{x.class_name}</Text><Text style={s.cell}>{[x.session_from,x.session_to].filter(Boolean).join('-')}</Text></TouchableOpacity>)}</View></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#eef3f8'},body:{padding:16,maxWidth:1100,width:'100%',alignSelf:'center',gap:12},nav:{flexDirection:'row',gap:8},title:{fontSize:25,fontWeight:'900'},tabs:{flexDirection:'row',flexWrap:'wrap',gap:8},tab:{padding:12,borderRadius:7,backgroundColor:'#fff',borderWidth:1,borderColor:'#cbd5e1'},active:{backgroundColor:'#174c36'},card:{backgroundColor:'#fff',padding:16,borderRadius:10,gap:14},heading:{fontSize:18,fontWeight:'800',marginTop:8},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,alignItems:'flex-end'},input:{borderWidth:1,borderColor:'#b8c2cc',borderRadius:6,padding:10,backgroundColor:'#fff'},light:{borderWidth:1,borderColor:'#94a3b8',padding:11,borderRadius:6,backgroundColor:'#f8fafc'},primary:{padding:13,borderRadius:7,backgroundColor:'#1769aa',alignItems:'center'},ok:{backgroundColor:'#198754',padding:9,borderRadius:5},danger:{backgroundColor:'#c62828',padding:9,borderRadius:5},white:{color:'#fff',fontWeight:'800'},bold:{fontWeight:'700'},disabled:{opacity:.4},actions:{flexDirection:'row',flexWrap:'wrap',gap:10,alignItems:'center'},row:{flexDirection:'row',padding:10,borderBottomWidth:1,borderBottomColor:'#ddd'},check:{width:40,fontSize:20},cell:{flex:1,minWidth:120},notice:{padding:13,backgroundColor:'#f1f5f9',gap:6},red:{color:'#b91c1c',fontWeight:'800'},green:{color:'#15803d',fontWeight:'800'},request:{flexDirection:'row',flexWrap:'wrap',gap:10,borderWidth:1,borderColor:'#d5dde5',padding:12,borderRadius:6}});
