import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Alert,Image,Linking,Modal,Platform,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import {SafeAreaView} from 'react-native-safe-area-context';
import AcademyHeader from '../components/AcademyHeader';
import {Select} from '../components/StudentDirectory';
import {Button,Card,Field} from '../components/ui';
import {api,API_BASE} from '../lib/api';
import {SUBJECTS} from '../lib/subjects';

const emptyForm={staff_id:'',name:'',mobile:'',whatsapp:'',gender:'',joining_date:'',subject:'',login_id:'',password:''};
export default function Teachers(){
 const [list,setList]=useState<any[]>([]),[form,setForm]=useState<any>(emptyForm),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editingId,setEditingId]=useState<number|null>(null),[documentTeacher,setDocumentTeacher]=useState<any>(null),[documents,setDocuments]=useState<any[]>([]),[documentsLoading,setDocumentsLoading]=useState(false);
 const load=async()=>{setLoading(true);try{const data=await api('/api/teachers');setList(data.teachers||[])}catch(e:any){Alert.alert('Error',e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);const set=(key:string,value:string)=>setForm((x:any)=>({...x,[key]:value}));
 const uploadPhoto=async(t:any)=>{const picked=await DocumentPicker.getDocumentAsync({type:'image/*',copyToCacheDirectory:true});if(picked.canceled)return;const f:any=picked.assets[0],body=new FormData();if(f.file)body.append('photo',f.file);else body.append('photo',{uri:f.uri,name:f.name||'teacher.jpg',type:f.mimeType||'image/jpeg'} as any);try{await api('/api/teachers/'+t.id+'/photo',{method:'POST',body});await load();Alert.alert('Updated','Teacher photo compressed and uploaded.')}catch(e:any){Alert.alert('Photo upload',e.message)}};
 const saveTeacher=async()=>{if(!form.staff_id.trim()||!form.name.trim())return Alert.alert('Required','Staff ID and name are required.');setSaving(true);try{if(editingId){await api('/api/teachers/'+editingId,{method:'PUT',body:JSON.stringify(form)});Alert.alert('Updated','Teacher data updated successfully.')}else{const data=await api('/api/teachers',{method:'POST',body:JSON.stringify(form)});Alert.alert('Teacher Added','User ID: '+data.credentials.login_id+'\nPassword: '+data.credentials.initial_password)}setForm(emptyForm);setEditingId(null);await load()}catch(e:any){Alert.alert('Error',e.message)}finally{setSaving(false)}};
 const startEdit=(t:any)=>{setEditingId(Number(t.id));setForm({staff_id:t.staff_id||'',name:t.name||'',mobile:t.mobile||'',whatsapp:t.whatsapp||'',gender:t.gender||'',joining_date:String(t.joining_date||'').slice(0,10),subject:t.subject||'',login_id:t.login_id||'',password:''})};
 const toggleStatus=async(t:any)=>{try{await api('/api/teachers/'+t.id+'/status',{method:'PATCH',body:JSON.stringify({is_active:t.user_active===false})});await load()}catch(e:any){Alert.alert('Status',e.message)}};
 const loadDocuments=async(t:any)=>{setDocumentTeacher(t);setDocumentsLoading(true);try{const data=await api('/api/teachers/'+t.id+'/documents');setDocuments(data.documents||[])}catch(e:any){Alert.alert('Documents',e.message)}finally{setDocumentsLoading(false)}};
 const uploadDocument=async()=>{if(!documentTeacher)return;const picked=await DocumentPicker.getDocumentAsync({type:['image/*','application/pdf'],copyToCacheDirectory:true});if(picked.canceled)return;const f:any=picked.assets[0],body=new FormData();if(f.file)body.append('file',f.file);else body.append('file',{uri:f.uri,name:f.name||'document',type:f.mimeType||'application/octet-stream'} as any);body.append('document_title',f.name||'Teacher document');body.append('document_type','other');try{await api('/api/teachers/'+documentTeacher.id+'/documents',{method:'POST',body});await loadDocuments(documentTeacher);Alert.alert('Uploaded','Teacher document compressed and uploaded to Cloudinary.')}catch(e:any){Alert.alert('Upload failed',e.message)}};
 const downloadDocument=(d:any)=>{if(Platform.OS==='web'){const a=window.document.createElement('a');a.href=d.file_url;a.target='_blank';a.download=d.document_title||'teacher-document';window.document.body.appendChild(a);a.click();a.remove()}else Linking.openURL(d.file_url)};
 const deleteDocument=(d:any)=>Alert.alert('Delete document','Delete '+(d.document_title||'this document')+'?',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{await api('/api/teachers/documents/'+d.id,{method:'DELETE'});await loadDocuments(documentTeacher)}catch(e:any){Alert.alert('Delete failed',e.message)}}}]);
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><AcademyHeader/><Text style={s.title}>Teachers & Staff</Text><Text style={s.help}>Default User ID is the first part of the name. Default password is the Staff ID.</Text>
 <View style={s.formCard}><Text style={s.sectionTitle}>{editingId?'Update Teacher':'Add Teacher'}</Text><View style={s.formGrid}><Field placeholder="Staff ID *" value={form.staff_id} onChangeText={(v:string)=>set('staff_id',v)} style={s.field}/><Field placeholder="Full name *" value={form.name} onChangeText={(v:string)=>set('name',v)} style={s.field}/><Field placeholder="Mobile" value={form.mobile} onChangeText={(v:string)=>set('mobile',v)} style={s.field} keyboardType="phone-pad"/><Field placeholder="WhatsApp" value={form.whatsapp} onChangeText={(v:string)=>set('whatsapp',v)} style={s.field} keyboardType="phone-pad"/><View style={s.selectField}><Select label="Gender" value={form.gender} onChange={v=>set('gender',v)} options={[{value:'',label:'Select gender'},{value:'Male',label:'Male'},{value:'Female',label:'Female'}]}/></View><Field placeholder="Joining date (YYYY-MM-DD)" value={form.joining_date} onChangeText={(v:string)=>set('joining_date',v)} style={s.field}/><View style={s.selectField}><Select label="Subject" value={form.subject} onChange={v=>set('subject',v)} options={[{value:'',label:'Select subject'},...SUBJECTS.map(v=>({value:v,label:v}))]}/></View><Field placeholder="User ID (auto if blank)" value={form.login_id} onChangeText={(v:string)=>set('login_id',v)} autoCapitalize="none" style={s.field}/><Field placeholder="Password (Staff ID if blank)" value={form.password} onChangeText={(v:string)=>set('password',v)} secureTextEntry style={s.field}/></View><Button title={saving?'Saving...':editingId?'Update Teacher':'Add Teacher'} onPress={saveTeacher}/>{editingId&&<TouchableOpacity onPress={()=>{setEditingId(null);setForm(emptyForm)}} style={s.cancelButton}><Text style={s.cancelText}>Cancel Edit</Text></TouchableOpacity>}</View>
 <Text style={s.sectionTitle}>Teacher List ({list.length})</Text>{loading?<ActivityIndicator size="large" color="#1565c0"/>:list.map(t=><Card key={t.id}><View style={s.teacherRow}>{t.photo_url?<Image source={{uri:/^https?:/.test(t.photo_url)?t.photo_url:API_BASE+t.photo_url}} style={s.avatar}/>:<View style={s.avatar}><Text style={s.avatarText}>{String(t.name||'?').charAt(0)}</Text></View>}<View style={s.teacherInfo}><Text style={s.teacherName}>{t.name}</Text><Text style={s.meta}>Staff ID: {t.staff_id} · User ID: {t.login_id||'Not created'}</Text><Text style={s.meta}>{t.gender||'-'} · {t.mobile||'-'} · WhatsApp {t.whatsapp||'-'}</Text></View><View style={s.teacherActions}><TouchableOpacity onPress={()=>startEdit(t)} style={s.editButton}><Text style={s.white}>Edit</Text></TouchableOpacity><TouchableOpacity onPress={()=>uploadPhoto(t)} style={s.photoButton}><Text style={s.white}>Photo</Text></TouchableOpacity><TouchableOpacity onPress={()=>loadDocuments(t)} style={s.documentButton}><Text style={s.white}>Documents</Text></TouchableOpacity><TouchableOpacity onPress={()=>toggleStatus(t)} style={[s.status,t.user_active===false&&s.inactive]}><Text style={s.white}>{t.user_active===false?'Inactive':'Active'}</Text></TouchableOpacity></View></View></Card>)}</ScrollView>
 <Modal visible={!!documentTeacher} transparent animationType="fade" onRequestClose={()=>setDocumentTeacher(null)}><View style={s.modalBackdrop}><View style={s.modalCard}><View style={s.modalHeader}><View><Text style={s.sectionTitle}>Teacher Documents</Text><Text style={s.meta}>{documentTeacher?.name} · Staff ID: {documentTeacher?.staff_id}</Text></View><TouchableOpacity onPress={()=>setDocumentTeacher(null)}><Text style={s.close}>×</Text></TouchableOpacity></View><TouchableOpacity onPress={uploadDocument} style={s.uploadButton}><Text style={s.white}>+ Upload Image / PDF</Text></TouchableOpacity><ScrollView style={{maxHeight:430}}>{documentsLoading?<ActivityIndicator style={{margin:30}}/>:documents.length===0?<Text style={s.empty}>No documents uploaded.</Text>:documents.map(d=><View key={d.id} style={s.documentRow}><View style={{flex:1}}><Text style={s.documentTitle}>{d.document_title||d.document_type}</Text><Text style={s.meta}>{String(d.uploaded_at||'').slice(0,10)}</Text></View><TouchableOpacity onPress={()=>Linking.openURL(d.file_url)} style={s.viewButton}><Text style={s.white}>View</Text></TouchableOpacity><TouchableOpacity onPress={()=>downloadDocument(d)} style={s.downloadButton}><Text style={s.white}>Download</Text></TouchableOpacity><TouchableOpacity onPress={()=>deleteDocument(d)} style={s.deleteButton}><Text style={s.white}>Delete</Text></TouchableOpacity></View>)}</ScrollView></View></View></Modal></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f3f7f5'},content:{width:'100%',maxWidth:980,alignSelf:'center',padding:16,paddingBottom:50},title:{fontSize:27,fontWeight:'900',color:'#193b2c',marginTop:6},help:{color:'#63736b',marginTop:4,marginBottom:16},formCard:{backgroundColor:'#fff',borderRadius:16,padding:16,marginBottom:24,borderWidth:1,borderColor:'#d9e5dd'},sectionTitle:{fontSize:18,fontWeight:'900',color:'#214333',marginBottom:12},formGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},field:{flexGrow:1,width:'31%',minWidth:220},selectField:{flexGrow:1,width:'31%',minWidth:220,marginBottom:10},teacherRow:{flexDirection:'row',alignItems:'center',gap:12},avatar:{width:46,height:46,borderRadius:23,backgroundColor:'#dceee3',alignItems:'center',justifyContent:'center'},avatarText:{color:'#17613c',fontSize:18,fontWeight:'900'},teacherInfo:{flex:1},teacherName:{fontSize:16,fontWeight:'900',color:'#233a2e'},meta:{color:'#687970',marginTop:3,fontSize:12},teacherActions:{gap:5},editButton:{backgroundColor:'#d68a00',padding:7,borderRadius:6},photoButton:{backgroundColor:'#1764a5',padding:7,borderRadius:6},documentButton:{backgroundColor:'#6741d9',padding:7,borderRadius:6},status:{backgroundColor:'#21834f',borderRadius:20,padding:7},inactive:{backgroundColor:'#b23442'},white:{color:'#fff',fontSize:11,fontWeight:'800'},cancelButton:{borderWidth:1,borderColor:'#64748b',padding:11,borderRadius:8,marginTop:7},cancelText:{textAlign:'center',fontWeight:'800'},modalBackdrop:{flex:1,backgroundColor:'rgba(15,23,42,.62)',alignItems:'center',justifyContent:'center',padding:16},modalCard:{width:'100%',maxWidth:820,maxHeight:'90%',backgroundColor:'#fff',borderRadius:14,padding:18},modalHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',marginBottom:14},close:{fontSize:30,fontWeight:'800',color:'#334155'},uploadButton:{backgroundColor:'#1764a5',padding:12,borderRadius:8,alignItems:'center',marginBottom:12},empty:{textAlign:'center',color:'#64748b',padding:28},documentRow:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:7,borderTopWidth:1,borderTopColor:'#e2e8f0',paddingVertical:11},documentTitle:{fontWeight:'800',color:'#1e293b'},viewButton:{backgroundColor:'#0e7490',padding:8,borderRadius:6},downloadButton:{backgroundColor:'#21834f',padding:8,borderRadius:6},deleteButton:{backgroundColor:'#b23442',padding:8,borderRadius:6}});