import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Image,Linking,Modal,ScrollView,Text,TouchableOpacity,Pressable,StyleSheet,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import AcademyHeader from '../components/AcademyHeader';
import {API_BASE,api} from '../lib/api';
import {clearSession,getUser} from '../lib/auth';

const items:any[]=[
 ['Attendance','/attendance','#157347'],
 ['Marks Entry','/marks','#2369b3'],['Terminal Exam','/terminal-exams','#7b4ba5'],['Class Results','/class-results','#16856b'],
];
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening';}
function date(value:any){return String(value||'').slice(0,10);}
export default function Teacher(){
 const [roomMenu,setRoomMenu]=useState(false),[teacher,setTeacher]=useState<any>(null),[routines,setRoutines]=useState<any[]>([]),[notices,setNotices]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{void(async()=>{try{const [profile,routineData,noticeData]=await Promise.all([api('/api/teachers/me'),api('/api/routines'),api('/api/notices')]);setTeacher(profile.teacher);setRoutines((routineData.routines||[]).filter((item:any)=>item.file_url));setNotices((noticeData.notices||[]).slice(0,4));}finally{setLoading(false);}})();},[]);
 const name=teacher?.name||teacher?.full_name||(getUser as any)?.full_name||'Teacher';const first=String(name).trim().split(/\s+/)[0];
 const photo=teacher?.photo_url?(/^https?:/.test(teacher.photo_url)?teacher.photo_url:`${API_BASE}${teacher.photo_url}`):null;
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><AcademyHeader extraActions={<><TouchableOpacity style={[s.headerItem,{backgroundColor:'#c56a14'}]} onPress={()=>setRoomMenu(true)}><Text style={s.headerText}>Room</Text></TouchableOpacity>{items.map(([title,path,color])=><TouchableOpacity key={title} style={[s.headerItem,{backgroundColor:color}]} onPress={()=>router.push(path as any)}><Text style={s.headerText}>{title}</Text></TouchableOpacity>)}</>}/>
 <View style={s.profile}>{photo?<Image source={{uri:photo}} style={s.photo}/>:<View style={[s.photo,s.avatar]}><Text style={s.initial}>{first.charAt(0)}</Text></View>}<View style={{flex:1}}><Text style={s.greeting}>{greeting()}, {first}</Text><Text style={s.title}>{first}'s Dashboard</Text></View></View>
 {loading?<ActivityIndicator color="#17643f"/>:<>
 <View style={s.routine}><Text style={s.sectionLabel}>PUBLISHED ROUTINE</Text>{routines.length?routines.map(item=>{const url=/^https?:/.test(item.file_url)?item.file_url:`${API_BASE}${item.file_url}`;return <TouchableOpacity key={item.id} style={s.routineItem} onPress={()=>Linking.openURL(url)}><Text style={s.routineTitle}>{item.title||'Published Routine'}</Text><Text style={s.routineMeta}>{date(item.routine_date||item.published_at)}</Text><Image source={{uri:url}} resizeMode="contain" style={s.routineImage}/><Text style={s.routineOpen}>Open JPG</Text></TouchableOpacity>}):<Text style={s.noRoutine}>No routine published.</Text>}</View>
 <TouchableOpacity style={s.noticeWrap} onPress={()=>router.push('/notices')}><View style={s.sectionRow}><Text style={s.noticeHeading}>Current Notices</Text><Text style={s.open}>View all →</Text></View>{notices.length?notices.map(n=><View key={n.id} style={s.notice}><Text style={s.noticeTitle}>{n.title}</Text><Text style={s.meta}>{n.notice_type||'Notice'} · {date(n.published_at)}</Text></View>):<Text style={s.meta}>No current notice.</Text>}</TouchableOpacity>
 </>}
 <View style={s.grid}>{items.map(([title,path,color])=><TouchableOpacity key={title} style={[s.card,{borderLeftColor:color}]} onPress={()=>router.push(path as any)}><Text style={[s.cardText,{color}]}>{title}</Text><Text style={s.open}>Open →</Text></TouchableOpacity>)}</View>

 </ScrollView><Modal visible={roomMenu} transparent animationType="fade" onRequestClose={()=>setRoomMenu(false)}><Pressable style={s.modalBackdrop} onPress={()=>setRoomMenu(false)}><View style={s.modal} onStartShouldSetResponder={()=>true}><View style={s.modalHead}><Text style={s.modalTitle}>Room</Text><TouchableOpacity onPress={()=>setRoomMenu(false)}><Text style={s.close}>X</Text></TouchableOpacity></View>{[['Room Problems','/problems'],['Student Behaviour','/behavior'],['Student Illness / Problem','/illness']].map(([label,path])=><Pressable key={path} style={({pressed})=>[s.modalItem,pressed&&s.modalItemActive]} onPress={()=>{setRoomMenu(false);router.push(path as any)}}><Text style={s.modalText}>{label}</Text></Pressable>)}</View></Pressable></Modal></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f2f7f4'},content:{width:'100%',maxWidth:900,alignSelf:'center',padding:16,paddingBottom:40},profile:{flexDirection:'row',alignItems:'center',gap:13,marginVertical:10},photo:{width:62,height:62,borderRadius:31,borderWidth:2,borderColor:'#91b6a1'},avatar:{backgroundColor:'#17643f',alignItems:'center',justifyContent:'center'},initial:{color:'#fff',fontSize:26,fontWeight:'900'},greeting:{color:'#557266',fontWeight:'700'},title:{fontSize:25,fontWeight:'900',color:'#173d2b',marginTop:2},routine:{backgroundColor:'#174f75',padding:17,borderRadius:15,marginBottom:12},sectionLabel:{color:'#bfe1f4',fontSize:11,fontWeight:'900'},routineItem:{backgroundColor:'#fff',borderRadius:10,padding:10,marginTop:10},routineTitle:{color:'#173d2b',fontSize:17,fontWeight:'900'},routineMeta:{color:'#728077',marginTop:3},routineImage:{width:'100%',height:360,backgroundColor:'#eef3f6',borderRadius:7,marginTop:8},routineOpen:{color:'#1768c5',marginTop:8,fontWeight:'900',textAlign:'center'},noRoutine:{color:'#fff',marginTop:10},meta:{color:'#728077',marginTop:4},open:{color:'#2870a8',marginTop:9,fontWeight:'800'},noticeWrap:{backgroundColor:'#fff',padding:15,borderRadius:15,marginBottom:15,borderWidth:1,borderColor:'#dbe6df'},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},noticeHeading:{fontSize:18,fontWeight:'900',color:'#783453'},notice:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#edf0ee'},noticeTitle:{fontWeight:'800',color:'#273b32'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{width:'48%',minWidth:240,flexGrow:1,backgroundColor:'#fff',borderRadius:14,borderLeftWidth:6,padding:18,elevation:2},cardText:{fontSize:17,fontWeight:'900'},modalBackdrop:{flex:1,backgroundColor:"rgba(0,0,0,.5)",justifyContent:"center",alignItems:"center"},modal:{width:"90%",maxWidth:520,backgroundColor:"#fff",borderRadius:14,padding:16},modalHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:10},modalTitle:{fontSize:20,fontWeight:"900",color:"#173d2b"},close:{fontSize:20,fontWeight:"900"},modalItem:{padding:15,borderWidth:1,borderColor:"#dbe6df",borderRadius:9,marginVertical:5},modalItemActive:{backgroundColor:"#dbeafe",borderColor:"#1768c5"},modalText:{fontSize:16,fontWeight:"900",color:"#263d54"},headerItem:{paddingHorizontal:9,paddingVertical:9,borderRadius:7},headerText:{color:"#fff",fontSize:11,fontWeight:"800"},logout:{backgroundColor:'#b52d3a',padding:14,borderRadius:10,marginTop:18},logoutText:{color:'#fff',textAlign:'center',fontWeight:'800'}});

