import React,{useState} from 'react';
import {Alert,Platform,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import * as LocalAuthentication from 'expo-local-authentication';
import AcademyHeader from '../components/AcademyHeader';
import {Field} from '../components/ui';
import {api} from '../lib/api';
import {saveRoleBiometricToken} from '../lib/guardianDevice';
export default function TeacherSecurity(){
 const [password,setPassword]=useState(''),[mpin,setMpin]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false);
 const saveMpin=async()=>{if(!/^\d{6}$/.test(mpin))return Alert.alert('Invalid','mPIN must be exactly 6 digits.');if(mpin!==confirm)return Alert.alert('Invalid','mPIN confirmation does not match.');setBusy(true);try{await api('/api/auth/set-mpin',{method:'POST',body:JSON.stringify({current_password:password,mpin})});setPassword('');setMpin('');setConfirm('');Alert.alert('Saved','Teacher mPIN generated successfully.');}catch(e:any){Alert.alert('Error',e.message);}finally{setBusy(false);}};
 const fingerprint=async()=>{if(Platform.OS==='web')return Alert.alert('Mobile only','Fingerprint setup is available in the installed mobile app.');try{const compatible=await LocalAuthentication.hasHardwareAsync();const enrolled=await LocalAuthentication.isEnrolledAsync();if(!compatible||!enrolled)return Alert.alert('Unavailable','Set up fingerprint in the phone settings first.');const check=await LocalAuthentication.authenticateAsync({promptMessage:'Confirm fingerprint'});if(!check.success)return;const data=await api('/api/biometric/register',{method:'POST',body:JSON.stringify({device_name:'Teacher mobile'})});const profile=await api('/api/teachers/me');await saveRoleBiometricToken('teacher',data.device_token,profile?.teacher?.login_id||profile?.teacher?.id);Alert.alert('Enabled','Teacher fingerprint login is registered on this device.');}catch(e:any){Alert.alert('Error',e.message);}};
 return <SafeAreaView style={s.page}><View style={s.body}><AcademyHeader/><Text style={s.title}>Teacher Login Security</Text><Text style={s.help}>Generate a 6 digit mPIN and register this mobile fingerprint.</Text><Field placeholder="Current password" secureTextEntry value={password} onChangeText={setPassword}/><Field placeholder="6 digit mPIN" secureTextEntry keyboardType="numeric" value={mpin} onChangeText={x=>setMpin(x.replace(/\D/g,'').slice(0,6))}/><Field placeholder="Confirm mPIN" secureTextEntry keyboardType="numeric" value={confirm} onChangeText={x=>setConfirm(x.replace(/\D/g,'').slice(0,6))}/><TouchableOpacity disabled={busy} onPress={saveMpin} style={s.primary}><Text style={s.white}>{busy?'Saving...':'Generate / Change mPIN'}</Text></TouchableOpacity><TouchableOpacity onPress={fingerprint} style={s.secondary}><Text style={s.blue}>Enable Fingerprint Login</Text></TouchableOpacity></View></SafeAreaView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f2f7f4'},body:{width:'100%',maxWidth:650,alignSelf:'center',padding:16},title:{fontSize:25,fontWeight:'900',color:'#173d2b',marginTop:10},help:{color:'#66776e',marginVertical:10},primary:{backgroundColor:'#17643f',padding:14,borderRadius:9,marginTop:8},white:{color:'#fff',fontWeight:'900',textAlign:'center'},secondary:{borderWidth:1,borderColor:'#1764a5',padding:14,borderRadius:9,marginTop:12},blue:{color:'#1764a5',fontWeight:'900',textAlign:'center'}});
