import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import AcademyHeader from '../components/AcademyHeader';
import {Field} from '../components/ui';import {Select} from '../components/StudentDirectory';
import {api} from '../lib/api';import {SUBJECTS} from '../lib/subjects';import {getUser} from '../lib/auth';import {STUDENT_CLASSES} from '../lib/studentClasses';
const blank={subject_name:'',full_marks:'',exam_date:'',teacher_id:''};
export default function TerminalExams(){
 const [admin,setAdmin]=useState(false),[teachers,setTeachers]=useState<any[]>([]),[exams,setExams]=useState<any[]>([]),[form,setForm]=useState<any>({exam_name:'Terminal Exam',class_name:'',session_name:'2026',subjects:[{...blank}]}),[entry,setEntry]=useState<any>(null),[students,setStudents]=useState<any[]>([]);
 const load=async()=>{const u=await getUser<any>();const manage=['admin','super_admin'].includes(u?.role);setAdmin(manage);const calls:any[]=[api('/api/terminal-exams')];if(manage)calls.push(api('/api/teachers'));const data=await Promise.all(calls);setExams(data[0].exams||[]);if(manage)setTeachers(data[1].teachers||[]);};
 useEffect(()=>{void load().catch(e=>Alert.alert('Error',e.message));},[]);
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 const subject=(i:number,k:string,v:string)=>setForm((x:any)=>({...x,subjects:x.subjects.map((a:any,n:number)=>n===i?{...a,[k]:v}:a)}));
 const create=async()=>{try{await api('/api/terminal-exams',{method:'POST',body:JSON.stringify(form)});setForm({exam_name:'Terminal Exam',class_name:'',session_name:'2026',subjects:[{...blank}]});await load();Alert.alert('Created','Exam and teacher assignments created.');}catch(e:any){Alert.alert('Error',e.message);}};
 const open=async(id:number)=>{try{const d=await api(`/api/terminal-exams/subjects/${id}/entry`);setEntry(d.assignment);setStudents((d.students||[]).map((x:any)=>({...x,mark:x.obtained_marks===null||x.obtained_marks===undefined?'':String(x.obtained_marks),absent:x.obtained_marks===null&&x.remarks==='Absent'})));}catch(e:any){Alert.alert('Error',e.message);}};
 const submit=async()=>{if(students.some(x=>!x.absent&&x.mark===''))return Alert.alert('Required','Enter marks or choose Absent for every student.');try{await api(`/api/terminal-exams/subjects/${entry.id}/submit`,{method:'POST',body:JSON.stringify({entries:students.map(x=>({student_id:x.student_id,obtained_marks:x.absent?null:Number(x.mark)}))})});setEntry(null);setStudents([]);await load();Alert.alert('Submitted','Marks submitted and locked.');}catch(e:any){Alert.alert('Error',e.message);}};
 const publish=async(id:number)=>{try{await api(`/api/terminal-exams/${id}/publish`,{method:'PATCH'});await load();Alert.alert('Published','Complete terminal result published.');}catch(e:any){Alert.alert('Cannot publish',e.message);}};
 const unpublish=async(id:number)=>{try{await api(`/api/terminal-exams/${id}/unpublish`,{method:'PATCH'});await load();Alert.alert('Unpublished','Result reopened for Admin correction.');}catch(e:any){Alert.alert('Error',e.message);}};
 return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.body}><AcademyHeader/><View style={s.nav}><TouchableOpacity onPress={()=>router.back()} style={s.navButton}><Text style={s.navText}>← Back</Text></TouchableOpacity><TouchableOpacity onPress={()=>router.push(admin?'/superadmin':'/teacher')} style={s.navButton}><Text style={s.navText}>⌂ Home</Text></TouchableOpacity></View><Text style={s.title}>Terminal Exam</Text>
 {entry?<><TouchableOpacity onPress={()=>setEntry(null)}><Text style={s.link}>← Back to exams</Text></TouchableOpacity><Text style={s.heading}>{entry.exam_name} · Class {entry.class_name}</Text><Text style={s.help}>{entry.subject_name} · Full Marks {entry.full_marks} · {String(entry.exam_date||'').slice(0,10)}</Text>{students.map((x,i)=><View key={x.student_id} style={s.student}><Text style={s.sl}>{i+1}</Text><View style={{flex:1}}><Text style={s.bold}>{x.student_name}</Text><Text style={s.help}>Reg. {x.registration_no}</Text></View><TextInput editable={entry.status!=='submitted'||admin} value={x.mark} onChangeText={v=>setStudents(a=>a.map(y=>y.student_id===x.student_id?{...y,mark:v.replace(/[^0-9.]/g,''),absent:false}:y))} keyboardType="numeric" style={s.mark}/><TouchableOpacity onPress={()=>setStudents(a=>a.map(y=>y.student_id===x.student_id?{...y,absent:!y.absent,mark:''}:y))} style={[s.absent,x.absent&&s.absentOn]}><Text style={x.absent?s.white:s.red}>{x.absent?'Absent':'Mark Absent'}</Text></TouchableOpacity></View>)}{(entry.status!=='submitted'||admin)&&<TouchableOpacity onPress={submit} style={s.primary}><Text style={s.white}>Submit & Lock Marks</Text></TouchableOpacity>}</>:
 <>{admin&&<View style={s.panel}><Text style={s.heading}>Create Terminal Exam</Text><Field placeholder="Exam name" value={form.exam_name} onChangeText={(v:string)=>set('exam_name',v)}/><Select label="Class" value={form.class_name} onChange={v=>set('class_name',v)} options={[{value:'',label:'Select class'},...STUDENT_CLASSES.map(v=>({value:v,label:v}))]}/><Field placeholder="Session" value={form.session_name} onChangeText={(v:string)=>set('session_name',v)}/>{form.subjects.map((x:any,i:number)=><View key={i} style={s.subject}><View style={s.flex}><Select label="Subject" value={x.subject_name} onChange={v=>subject(i,'subject_name',v)} options={[{value:'',label:'Select subject'},...SUBJECTS.map(v=>({value:v,label:v}))]}/></View><Field placeholder="Full marks" value={x.full_marks} onChangeText={(v:string)=>subject(i,'full_marks',v)} keyboardType="numeric" style={s.small}/><Field placeholder="Exam date YYYY-MM-DD" value={x.exam_date} onChangeText={(v:string)=>subject(i,'exam_date',v)} style={s.date}/><View style={s.teacher}><Select searchable label="Teacher" value={String(x.teacher_id)} onChange={v=>subject(i,'teacher_id',v)} options={[{value:'',label:'Assign teacher'},...teachers.map(t=>({value:String(t.id),label:t.name}))]}/></View></View>)}<TouchableOpacity onPress={()=>setForm((x:any)=>({...x,subjects:[...x.subjects,{...blank}]}))}><Text style={s.link}>+ Add subject</Text></TouchableOpacity><TouchableOpacity onPress={create} style={s.primary}><Text style={s.white}>Create & Assign</Text></TouchableOpacity></View>}
 <Text style={s.heading}>{admin?'Terminal Exams':'My Assigned Subjects'}</Text>{exams.map(e=><View key={e.id} style={s.card}><Text style={s.bold}>{e.exam_name} · Class {e.class_name}</Text><Text style={s.help}>{e.submitted_count}/{e.subject_count} subjects submitted · {e.status}</Text>{(e.subjects||[]).map((x:any)=><TouchableOpacity key={x.id} onPress={()=>open(x.id)} style={s.assignment}><Text style={s.bold}>{x.subject_name} · Full {x.full_marks}</Text><Text style={s.help}>{x.teacher_name||'Unassigned'} · {x.status}</Text></TouchableOpacity>)}{admin&&(e.status==='published'?<TouchableOpacity onPress={()=>unpublish(e.id)} style={[s.publish,{backgroundColor:'#b33b47'}]}><Text style={s.white}>Unpublish for Correction</Text></TouchableOpacity>:<TouchableOpacity onPress={()=>publish(e.id)} style={s.publish}><Text style={s.white}>Publish Complete Result</Text></TouchableOpacity>)}</View>)}</>}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({nav:{flexDirection:'row',gap:8,marginTop:8},navButton:{backgroundColor:'#e4eef8',paddingHorizontal:14,paddingVertical:9,borderRadius:8},navText:{color:'#174f7d',fontWeight:'900'},page:{flex:1,backgroundColor:'#f3f6fa'},body:{width:'100%',maxWidth:1050,alignSelf:'center',padding:16,paddingBottom:50},title:{fontSize:27,fontWeight:'900',color:'#173f68',marginVertical:12},heading:{fontSize:19,fontWeight:'900',color:'#263f58',marginVertical:10},help:{color:'#6e7d8b',fontSize:12,marginTop:3},panel:{backgroundColor:'#fff',padding:15,borderRadius:14,marginBottom:18},subject:{flexDirection:'row',flexWrap:'wrap',gap:8,alignItems:'center',paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#eee'},flex:{flex:1,minWidth:150},small:{width:100},date:{width:190},teacher:{width:210},primary:{backgroundColor:'#175e9d',padding:14,borderRadius:9,marginTop:10},publish:{backgroundColor:'#16814d',padding:11,borderRadius:8,marginTop:9},white:{color:'#fff',fontWeight:'900',textAlign:'center'},link:{color:'#1662a5',fontWeight:'900',marginVertical:10},card:{backgroundColor:'#fff',padding:15,borderRadius:13,marginBottom:11,borderWidth:1,borderColor:'#dbe4ed'},bold:{fontWeight:'900',color:'#273e55'},assignment:{backgroundColor:'#edf4fb',padding:11,borderRadius:8,marginTop:8},student:{flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#fff',padding:9,borderBottomWidth:1,borderBottomColor:'#e5e9ed'},sl:{width:28,textAlign:'center'},mark:{width:75,borderWidth:1,borderColor:'#aab8c5',borderRadius:7,padding:8,textAlign:'center'},absent:{borderWidth:1,borderColor:'#c83c48',padding:8,borderRadius:7},absentOn:{backgroundColor:'#c83c48'},red:{color:'#b52f3a',fontWeight:'800'}});
