import React,{useEffect,useMemo,useState}from'react';
import{Alert,Platform,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{Select}from'./StudentDirectory';
import{api}from'../lib/api';

const SUBJECTS=['Arabic','Art','Beng','Bio','Chem','Comp','Eng','Eng-I','Eng-II','Geo','Hind','Hist','L.Sc','Math','P.Sc','Phy','Sci'];
const GROUP_CLASSES:any={v_x:['V','VI','VII','VIII','IX','X'],xi_xii:['XI-A','XI-B','XII-A','XII-B']};
const empty=(date:string)=>({group_name:'v_x',exam_date:date,end_date:'',class_names:[] as string[],subject:'',start_time:'',end_time:'',room:'',teacher_ids:[] as string[],teacher_names:[] as string[],suppress_regular:true,duty_final:false});

export default function ExamRoutinePanel({teachers,initialDate}:{teachers:any[];initialDate:string}){
 const[open,setOpen]=useState(true),[form,setForm]=useState<any>(empty(initialDate)),[editing,setEditing]=useState(''),[month,setMonth]=useState(initialDate.slice(0,7)),[items,setItems]=useState<any[]>([]),[counts,setCounts]=useState<any[]>([]),[busy,setBusy]=useState(false);
 const classes=GROUP_CLASSES[form.group_name]||[];
 useEffect(()=>{void load()},[month]);
 async function load(){try{const d=await api('/api/routines/exams?month='+month);setItems(d.exams||[]);setCounts(d.duty_counts||[])}catch(e:any){Alert.alert('Exam routine',e.message)}}
 const dateField=(key:string,label:string)=><View style={s.field}><Text style={s.label}>{label}</Text>{Platform.OS==='web'?React.createElement('input',{type:'date',value:form[key]||'',onChange:(e:any)=>setForm((x:any)=>({...x,[key]:e.target.value})),style:webInput}):<TextInput value={form[key]} onChangeText={v=>setForm((x:any)=>({...x,[key]:v}))} placeholder="YYYY-MM-DD" style={s.input}/>}</View>;
 const timeField=(key:string,label:string)=><View style={s.smallField}><Text style={s.label}>{label}</Text>{Platform.OS==='web'?React.createElement('input',{type:'time',value:form[key]||'',onChange:(e:any)=>setForm((x:any)=>({...x,[key]:e.target.value})),style:webInput}):<TextInput value={form[key]} onChangeText={v=>setForm((x:any)=>({...x,[key]:v}))} placeholder="HH:MM" style={s.input}/>}</View>;
 const toggle=(key:'class_names'|'teacher_ids',value:string)=>setForm((x:any)=>{const on=x[key].includes(value),next=on?x[key].filter((v:string)=>v!==value):[...x[key],value];if(key==='teacher_ids')return{...x,teacher_ids:next,teacher_names:next.map((id:string)=>teachers.find(t=>String(t.id)===id)?.name||'Teacher')};return{...x,[key]:next}});
 async function save(){if(!form.class_names.length||!form.subject||!form.exam_date||!form.start_time||!form.end_time||!form.teacher_ids.length)return Alert.alert('Required','Select date, class, subject, time and duty teacher.');setBusy(true);try{await api('/api/routines/exams'+(editing?'/'+editing:''),{method:editing?'PUT':'POST',body:JSON.stringify(form)});setEditing('');setForm(empty(form.exam_date));setMonth(form.exam_date.slice(0,7));await load();Alert.alert('Saved','Exam routine saved.')}catch(e:any){Alert.alert('Error',e.message)}finally{setBusy(false)}}
 function edit(x:any){setEditing(String(x.id));setForm({...x,exam_date:String(x.exam_date).slice(0,10),end_date:x.end_date?String(x.end_date).slice(0,10):'',start_time:String(x.start_time).slice(0,5),end_time:String(x.end_time).slice(0,5),teacher_ids:(x.teacher_ids||[]).map(String)});setOpen(true)}
 async function remove(id:any){try{await api('/api/routines/exams/'+id,{method:'DELETE'});await load()}catch(e:any){Alert.alert('Error',e.message)}}
 async function final(x:any){try{await api('/api/routines/exams/'+x.id+'/final',{method:'PATCH',body:JSON.stringify({duty_final:!x.duty_final})});await load()}catch(e:any){Alert.alert('Error',e.message)}}
 function csv(){if(Platform.OS!=='web')return Alert.alert('Web only','CSV download is available on web.');const data=[['Date','Class','Subject','Time','Room','Teacher','Duty Final'],...items.map(x=>[x.exam_date,(x.class_names||[]).join(' / '),x.subject,String(x.start_time).slice(0,5)+'-'+String(x.end_time).slice(0,5),x.room||'',(x.teacher_names||[]).join(' / '),x.duty_final?'Yes':'No'])],text=data.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n'),url=URL.createObjectURL(new Blob([text],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='exam-duty-'+month+'.csv';a.click();URL.revokeObjectURL(url)}
 return <View style={s.wrap}><TouchableOpacity onPress={()=>setOpen(x=>!x)}><Text style={s.title}>{open?'¼':'¶'} Exam Routine  For Specific Dates</Text></TouchableOpacity>{open&&<>
  <Text style={s.help}>Add exams for one or more classes. Regular routine and coaching continue. Master routine is unchanged.</Text>
  <View style={s.formRow}><View style={s.field}><Text style={s.label}>Division</Text><Select label="Division" value={form.group_name} onChange={v=>setForm((x:any)=>({...x,group_name:v,class_names:[]}))} options={[{value:'v_x',label:'V-X'},{value:'xi_xii',label:'XI-XII'}]}/></View>{dateField('exam_date','Exam date')}{dateField('end_date','End date (optional)')}<View style={s.field}><Text style={s.label}>Subject</Text><Select label="Subject" value={form.subject} onChange={v=>setForm((x:any)=>({...x,subject:v}))} options={[{value:'',label:'Select subject'},...SUBJECTS.map(v=>({value:v,label:v}))]}/></View>{timeField('start_time','Start (24-hour)')}{timeField('end_time','End (24-hour)')}<View style={s.field}><Text style={s.label}>Room</Text><TextInput value={form.room} onChangeText={v=>setForm((x:any)=>({...x,room:v}))} placeholder="101, 102" style={s.input}/></View></View>
  <View style={s.box}><Text style={s.boxTitle}>Exam classes  multiple selection allowed</Text><View style={s.checks}>{classes.map((v:string)=><Check key={v} label={v} on={form.class_names.includes(v)} press={()=>toggle('class_names',v)}/>)}</View></View>
  <View style={s.box}><Text style={s.boxTitle}>Duty teachers  multiple selection allowed</Text><View style={s.checks}>{teachers.map(t=><Check key={t.id} label={t.name} on={form.teacher_ids.includes(String(t.id))} press={()=>toggle('teacher_ids',String(t.id))}/>)}</View></View>
  <TouchableOpacity onPress={()=>setForm((x:any)=>({...x,suppress_regular:!x.suppress_regular}))} style={[s.suppress,form.suppress_regular&&s.suppressOn]}><Text style={s.bold}>{form.suppress_regular?' ':''}Stop selected classes' regular periods when exam time overlaps</Text></TouchableOpacity>
  <View style={s.actions}><TouchableOpacity disabled={busy} onPress={save} style={s.primary}><Text style={s.white}>{busy?'Saving...':editing?'Update Exam':'Exam Save'}</Text></TouchableOpacity>{editing&&<TouchableOpacity onPress={()=>{setEditing('');setForm(empty(initialDate))}} style={s.secondary}><Text style={s.bold}>New / Cancel Edit</Text></TouchableOpacity>}</View>
  <View style={s.reportBar}><View><Text style={s.label}>Exam record month</Text>{Platform.OS==='web'?React.createElement('input',{type:'month',value:month,onChange:(e:any)=>setMonth(e.target.value),style:webInput}):<TextInput value={month} onChangeText={setMonth} style={s.input}/>}</View><TouchableOpacity onPress={csv} style={s.secondary}><Text style={s.bold}>Exam Duty Report CSV</Text></TouchableOpacity></View>
  <ScrollView horizontal><View style={s.table}><View style={s.tr}>{['Date','Class','Subject','Time','Room','Teacher','Duty Final','Edit / Delete'].map((h,i)=><Text key={h} style={[s.th,{width:i===7?150:i===5?190:130}]}>{h}</Text>)}</View>{items.map(x=><View key={x.id} style={s.tr}><Text style={s.td}>{x.exam_date}</Text><Text style={s.td}>{(x.class_names||[]).join(', ')}</Text><Text style={s.td}>{x.subject}</Text><Text style={s.td}>{String(x.start_time).slice(0,5)}-{String(x.end_time).slice(0,5)}</Text><Text style={s.td}>{x.room||'-'}</Text><Text style={[s.td,{width:190}]}>{(x.teacher_names||[]).join(', ')}</Text><TouchableOpacity onPress={()=>final(x)} style={[s.final,x.duty_final&&s.finalOn]}><Text style={s.bold}>{x.duty_final?' Final':'Set Final'}</Text></TouchableOpacity><View style={[s.rowActions,{width:150}]}><TouchableOpacity onPress={()=>edit(x)} style={s.edit}><Text>Edit</Text></TouchableOpacity><TouchableOpacity onPress={()=>remove(x.id)} style={s.del}><Text style={s.white}>Delete</Text></TouchableOpacity></View></View>)}</View></ScrollView>
  <Text style={s.countTitle}>Selected Month Exam Duty Count</Text><View style={s.countTable}>{counts.map(x=><View key={x.teacher_id} style={s.countRow}><Text style={{flex:1}}>{x.teacher_name}</Text><Text style={s.bold}>{x.duty_count}</Text></View>)}<View style={s.countTotal}><Text style={s.bold}>Total Duty</Text><Text style={s.bold}>{counts.reduce((n,x)=>n+Number(x.duty_count),0)}</Text></View></View>
 </>}</View>
}
function Check({label,on,press}:{label:string;on:boolean;press:()=>void}){return <TouchableOpacity onPress={press} style={[s.check,on&&s.checkOn]}><Text style={[s.checkText,on&&s.white]}>{on?' ':''}{label}</Text></TouchableOpacity>}
const webInput={height:40,border:'1px solid #b7c8d9',borderRadius:6,padding:'0 9px',background:'#fff'};
const s=StyleSheet.create({wrap:{backgroundColor:'#fff',borderWidth:1,borderColor:'#cad9e8',borderRadius:10,padding:13,marginTop:14},title:{fontSize:17,fontWeight:'900',color:'#173f77'},help:{color:'#526b84',marginVertical:12},formRow:{flexDirection:'row',flexWrap:'wrap',gap:9,alignItems:'flex-end'},field:{minWidth:155,flexGrow:1},smallField:{width:135},label:{fontWeight:'800',fontSize:12,color:'#36516e',marginBottom:4},input:{borderWidth:1,borderColor:'#b7c8d9',borderRadius:6,padding:10,backgroundColor:'#fff'},box:{borderWidth:1,borderColor:'#bdcfe1',borderRadius:8,padding:10,marginTop:10},boxTitle:{fontWeight:'900',color:'#233f5d',marginBottom:8},checks:{flexDirection:'row',flexWrap:'wrap',gap:6},check:{borderWidth:1,borderColor:'#b8c8d8',borderRadius:5,paddingHorizontal:8,paddingVertical:6},checkOn:{backgroundColor:'#1768c5',borderColor:'#1768c5'},checkText:{fontSize:12,color:'#263d54'},white:{color:'#fff',fontWeight:'900'},bold:{fontWeight:'900'},suppress:{backgroundColor:'#fff1ca',padding:11,borderRadius:7,marginTop:10},suppressOn:{borderWidth:1,borderColor:'#e5c24f'},actions:{flexDirection:'row',gap:8,marginTop:10},primary:{backgroundColor:'#1269c7',padding:11,borderRadius:6},secondary:{backgroundColor:'#e2ecf8',padding:11,borderRadius:6},reportBar:{flexDirection:'row',alignItems:'flex-end',gap:8,marginVertical:14,flexWrap:'wrap'},table:{borderWidth:1,borderColor:'#a9bfd8'},tr:{flexDirection:'row'},th:{width:130,padding:8,backgroundColor:'#d5e5f6',borderRightWidth:1,borderBottomWidth:1,borderColor:'#a9bfd8',fontWeight:'900'},td:{width:130,padding:8,borderRightWidth:1,borderBottomWidth:1,borderColor:'#c5d4e3'},final:{width:130,padding:8,borderRightWidth:1,borderBottomWidth:1,borderColor:'#c5d4e3',backgroundColor:'#fff0c9'},finalOn:{backgroundColor:'#bfe9ce'},rowActions:{flexDirection:'row',gap:5,padding:5,borderBottomWidth:1,borderColor:'#c5d4e3'},edit:{backgroundColor:'#e2ecf8',padding:7,borderRadius:5},del:{backgroundColor:'#b82935',padding:7,borderRadius:5},countTitle:{fontSize:17,fontWeight:'900',marginTop:18,color:'#173f77'},countTable:{maxWidth:650,borderWidth:1,borderColor:'#b7c9dc',marginTop:7},countRow:{flexDirection:'row',padding:8,borderBottomWidth:1,borderColor:'#c7d5e4'},countTotal:{flexDirection:'row',justifyContent:'space-between',padding:9,backgroundColor:'#d4e4f5'}});
