const express=require('express');const multer=require('multer');const fs=require('fs');const path=require('path');const pool=require('../db');const{auth,allow}=require('../middleware/auth');const asyncHandler=require('../utils/asyncHandler');const router=express.Router();const invoiceUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>{const allowed=file.mimetype.startsWith('image/')||file.mimetype==='application/pdf';cb(allowed?null:new Error('Only image and PDF invoice files are allowed'),allowed);}}).single('file');
let ready;
function schema(){if(!ready)ready=pool.query(`CREATE TABLE IF NOT EXISTS assets(
 id SERIAL PRIMARY KEY,asset_id VARCHAR(120) UNIQUE NOT NULL,name VARCHAR(200) NOT NULL,category VARCHAR(100),purchase_date DATE,bill_no VARCHAR(120),vendor_name VARCHAR(200),purchase_price NUMERIC(14,2) NOT NULL DEFAULT 0,annual_depreciation_rate NUMERIC(7,3) NOT NULL DEFAULT 0,accumulated_depreciation NUMERIC(14,2) NOT NULL DEFAULT 0,book_value NUMERIC(14,2) NOT NULL DEFAULT 0,allocation VARCHAR(250),custodian VARCHAR(200),status VARCHAR(30) NOT NULL DEFAULT 'Active',disposal_date DATE,disposal_price NUMERIC(14,2),disposal_reason TEXT,created_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());ALTER TABLE assets ADD COLUMN IF NOT EXISTS bill_file_url TEXT;ALTER TABLE assets ADD COLUMN IF NOT EXISTS bill_file_name VARCHAR(255);CREATE TABLE IF NOT EXISTS asset_maintenance(id SERIAL PRIMARY KEY,asset_id INTEGER REFERENCES assets(id) ON DELETE CASCADE,maintenance_date DATE NOT NULL DEFAULT CURRENT_DATE,description TEXT NOT NULL,cost NUMERIC(14,2) NOT NULL DEFAULT 0,vendor_name VARCHAR(200),created_by INTEGER REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`).catch(e=>{ready=null;throw e});return ready}
router.use(auth,allow('super_admin','admin'));
router.get('/',asyncHandler(async(req,res)=>{await schema();const r=await pool.query(`SELECT a.*,COALESCE((SELECT json_agg(m ORDER BY m.maintenance_date DESC) FROM asset_maintenance m WHERE m.asset_id=a.id),'[]') maintenance FROM assets a ORDER BY a.created_at DESC`);res.json({success:true,assets:r.rows})}));
router.post('/',asyncHandler(async(req,res)=>{await schema();const b=req.body||{};const price=Number(b.purchase_price||0);if(!String(b.asset_id||'').trim()||!String(b.name||'').trim()||!Number.isFinite(price)||price<0)return res.status(400).json({message:'Asset ID, name and valid purchase price are required.'});const r=await pool.query(`INSERT INTO assets(asset_id,name,category,purchase_date,bill_no,vendor_name,purchase_price,annual_depreciation_rate,book_value,allocation,custodian,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$7,$9,$10,$11) RETURNING *`,[String(b.asset_id).trim(),String(b.name).trim(),b.category||null,b.purchase_date||null,b.bill_no||null,b.vendor_name||null,price,Number(b.annual_depreciation_rate||0),b.allocation||null,b.custodian||null,req.user.userId]);res.status(201).json({success:true,asset:r.rows[0]})}));
router.post('/:id/invoice',invoiceUpload,asyncHandler(async(req,res)=>{await schema();if(!req.file)return res.status(400).json({message:'Choose a bill or invoice file.'});const asset=(await pool.query('SELECT id FROM assets WHERE id=$1',[req.params.id])).rows[0];if(!asset)return res.status(404).json({message:'Asset not found'});const dir=path.join(__dirname,'../../uploads/asset-invoices');fs.mkdirSync(dir,{recursive:true});const safe=String(req.file.originalname||'invoice').replace(/[^a-zA-Z0-9._-]/g,'_');const name=req.params.id+'-'+Date.now()+'-'+safe;fs.writeFileSync(path.join(dir,name),req.file.buffer);const url='/uploads/asset-invoices/'+name;const result=await pool.query('UPDATE assets SET bill_file_url=$1,bill_file_name=$2,updated_at=NOW() WHERE id=$3 RETURNING *',[url,req.file.originalname,req.params.id]);res.json({success:true,asset:result.rows[0]});}));
router.patch('/:id',asyncHandler(async(req,res)=>{await schema();const b=req.body||{};const fields=['allocation','custodian','status','name','category','vendor_name','bill_no','purchase_date','annual_depreciation_rate'];const set=[],values=[];for(const f of fields)if(b[f]!==undefined){values.push(b[f]);set.push(`${f}=$${values.length}`)}if(!set.length)return res.status(400).json({message:'No changes supplied.'});values.push(req.params.id);const r=await pool.query(`UPDATE assets SET ${set.join(',')},updated_at=NOW() WHERE id=$${values.length} RETURNING *`,values);if(!r.rowCount)return res.status(404).json({message:'Asset not found'});res.json({success:true,asset:r.rows[0]})}));
router.post('/:id/depreciation',asyncHandler(async(req,res)=>{await schema();const b=req.body||{};const asOf=new Date(b.as_of||new Date());const r=await pool.query('SELECT * FROM assets WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Asset not found'});const a=r.rows[0];const bought=a.purchase_date?new Date(a.purchase_date):asOf;const years=Math.max(0,(asOf-bought)/(365.25*24*3600*1000));const rate=Number(b.annual_depreciation_rate??a.annual_depreciation_rate)||0;const accumulated=Math.min(Number(a.purchase_price),Number(a.purchase_price)*rate/100*years);const book=Math.max(0,Number(a.purchase_price)-accumulated);const out=await pool.query('UPDATE assets SET annual_depreciation_rate=$1,accumulated_depreciation=$2,book_value=$3,updated_at=NOW() WHERE id=$4 RETURNING *',[rate,accumulated,book,req.params.id]);res.json({success:true,asset:out.rows[0]})}));
router.post('/:id/maintenance',asyncHandler(async(req,res)=>{await schema();const b=req.body||{};if(!String(b.description||'').trim())return res.status(400).json({message:'Maintenance description is required.'});const r=await pool.query('INSERT INTO asset_maintenance(asset_id,maintenance_date,description,cost,vendor_name,created_by) VALUES($1,COALESCE($2,CURRENT_DATE),$3,$4,$5,$6) RETURNING *',[req.params.id,b.maintenance_date,String(b.description).trim(),Number(b.cost||0),b.vendor_name||null,req.user.userId]);res.status(201).json({success:true,maintenance:r.rows[0]})}));
router.post('/:id/disposal',asyncHandler(async(req,res)=>{await schema();const b=req.body||{};const r=await pool.query(`UPDATE assets SET status='Disposed',disposal_date=COALESCE($1,CURRENT_DATE),disposal_price=$2,disposal_reason=$3,updated_at=NOW() WHERE id=$4 RETURNING *`,[b.disposal_date||null,Number(b.disposal_price||0),b.disposal_reason||null,req.params.id]);if(!r.rowCount)return res.status(404).json({message:'Asset not found'});res.json({success:true,asset:r.rows[0]})}));
module.exports=router;
