const express=require('express');const pool=require('../db');const {auth,allow}=require('../middleware/auth');const asyncHandler=require('../utils/asyncHandler');const router=express.Router();
router.get('/student/:id',auth,asyncHandler(async(req,res)=>{const r=await pool.query(`SELECT * FROM student_dues WHERE student_id=$1 ORDER BY created_at DESC`,[req.params.id]);res.json({success:true,dues:r.rows});}));
router.get('/student/:id/summary',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{
  const student=(await pool.query(`SELECT id,registration_no,student_name,class_name,sdf_book_no FROM students WHERE id=$1`,[req.params.id])).rows[0];
  if(!student)return res.status(404).json({success:false,message:'Student not found'});
  const dues=(await pool.query(`SELECT id,due_title,amount,due_date,remarks,status FROM student_dues WHERE student_id=$1 AND status='due' AND amount>0 ORDER BY due_date NULLS LAST,created_at`,[req.params.id])).rows;
  const isSdf=x=>/\bs\.?d\.?f\b|student development fund|bus fare|admission fee|registration fee/i.test(String(x.due_title||''));
  const monthlyDues=dues.filter(x=>/monthly|tuition|school fee|fees?/i.test(String(x.due_title||''))&&!isSdf(x));
  const sdfDues=dues.filter(isSdf);
  const tx=(await pool.query(`SELECT COALESCE(SUM(CASE WHEN transaction_type='deposit' THEN amount ELSE 0 END),0) total_deposit,COALESCE(SUM(CASE WHEN transaction_type='expense' THEN amount ELSE 0 END),0) total_expense FROM student_deposit_transactions WHERE student_id=$1`,[req.params.id])).rows[0];
  const totalDeposit=Number(tx.total_deposit||0),totalExpense=Number(tx.total_expense||0);
  res.json({success:true,student,monthly_dues:monthlyDues,monthly_due_total:monthlyDues.reduce((n,x)=>n+Number(x.amount||0),0),sdf_dues:sdfDues,sdf_due:Math.max(0,totalExpense-totalDeposit),sdf_balance:totalDeposit-totalExpense,total_deposit:totalDeposit,total_expense:totalExpense});
}));
router.post('/',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const b=req.body;const r=await pool.query(`INSERT INTO student_dues(student_id,due_title,amount,due_date,status,remarks,entered_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[b.student_id,b.due_title,b.amount,b.due_date||null,b.status||'due',b.remarks||null,req.user.userId]);res.status(201).json({success:true,due:r.rows[0]});}));
router.post('/bulk',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const b=req.body||{};const title=String(b.due_title||'').trim();const amount=Number(b.amount);const className=String(b.class_name||'*').trim();if(!title||!Number.isFinite(amount)||amount<=0)return res.status(400).json({success:false,message:'Due title and a positive amount are required'});const dueDate=b.due_date||null;const students=(await pool.query(className==='*'?'SELECT id FROM students WHERE is_active=TRUE':'SELECT id FROM students WHERE class_name=$1 AND is_active=TRUE',className==='*'?[]:[className])).rows;if(!students.length)return res.status(404).json({success:false,message:'No active students found for this class'});const result=await pool.query(`INSERT INTO student_dues(student_id,due_title,amount,due_date,status,remarks,entered_by) SELECT s.id,$1::text,$2::numeric,$3::date,'due',$4::text,$5::bigint FROM students s WHERE s.is_active=TRUE AND ($6::text='*' OR s.class_name=$6::text) AND NOT EXISTS (SELECT 1 FROM student_dues d WHERE d.student_id=s.id AND d.due_title=$1::text AND d.due_date IS NOT DISTINCT FROM $3::date AND d.status='due')`,[title,amount,dueDate,b.remarks||null,req.user.userId,className]);res.status(201).json({success:true,created:result.rowCount,skipped:students.length-result.rowCount,class_name:className})}));
router.patch('/:id',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const b=req.body;const r=await pool.query(`UPDATE student_dues SET due_title=$1,amount=$2,due_date=$3,status=$4,remarks=$5,updated_at=NOW() WHERE id=$6 RETURNING *`,[b.due_title,b.amount,b.due_date||null,b.status||'due',b.remarks||null,req.params.id]);res.json({success:true,due:r.rows[0]});}));
module.exports=router;
