const express=require('express');
const pool=require('../db');
const {auth,allow}=require('../middleware/auth');
const asyncHandler=require('../utils/asyncHandler');
const router=express.Router();
const roles=allow('super_admin','admin','office');
function blockOffice001(req,res,next){if(String(req.user?.loginId||'').toUpperCase()==='OFFICE-001')return res.status(403).json({success:false,message:'OFFICE-001 cannot generate gate passes'});next();}
async function notifyGuardian(client,studentId,token,departure,userId){
 const notice=await client.query(`INSERT INTO notices(title,notice_text,notice_type,published_by,is_active,published_at) VALUES($1,$2,'gate_pass',$3,TRUE,NOW()) RETURNING id`,['Gate Pass Generated',`Gate pass ${token} has been prepared. Departure: ${departure}.`,userId]);
 await client.query(`INSERT INTO notice_targets(notice_id,target_type,target_value) VALUES($1,'student',$2)`,[notice.rows[0].id,String(studentId)]);
}
const selectFields=`SELECT gp.*,to_char(gp.departure_at,'YYYY-MM-DD HH24:MI') departure_text,to_char(gp.expected_return_at,'YYYY-MM-DD HH24:MI') expected_return_text,to_char(gp.returned_at,'YYYY-MM-DD HH24:MI') returned_text,to_char(gp.printed_at,'YYYY-MM-DD HH24:MI') printed_text,s.registration_no,s.student_name,s.class_name,s.guardian_name,s.father_name,s.photo_url,r.room_name,u.full_name generated_by_name,pu.full_name printed_by_name FROM student_gate_passes gp JOIN students s ON s.id=gp.student_id LEFT JOIN rooms r ON r.id=s.room_id LEFT JOIN users u ON u.id=gp.generated_by LEFT JOIN users pu ON pu.id=gp.printed_by`;
router.get('/student/:registration',auth,roles,asyncHandler(async(req,res)=>{const q=await pool.query(`SELECT s.id,s.registration_no,s.student_name,s.class_name,s.guardian_name,s.father_name,s.photo_url,r.room_name FROM students s LEFT JOIN rooms r ON r.id=s.room_id WHERE s.registration_no=$1 AND s.is_active=TRUE`,[req.params.registration]);if(!q.rowCount)return res.status(404).json({success:false,message:'Active student not found'});res.json({success:true,student:q.rows[0]});}));
router.get('/',auth,roles,asyncHandler(async(req,res)=>{const args=[],where=[];if(req.query.year){args.push(String(req.query.year));where.push(`to_char(gp.departure_at,'YYYY')=$${args.length}`)}if(req.query.class_name){args.push(String(req.query.class_name));where.push(`s.class_name=$${args.length}`)}if(req.query.status){args.push(String(req.query.status));where.push(`gp.status=$${args.length}`)}else where.push("gp.status<>'draft'");if(req.query.q){args.push('%'+String(req.query.q)+'%');where.push(`(s.registration_no ILIKE $${args.length} OR s.student_name ILIKE $${args.length} OR gp.token_no ILIKE $${args.length})`)}const q=await pool.query(selectFields+' WHERE '+where.join(' AND ')+' ORDER BY gp.created_at DESC LIMIT 500',args);res.json({success:true,gate_passes:q.rows});}));
router.get('/:id',auth,roles,asyncHandler(async(req,res)=>{const q=await pool.query(selectFields+' WHERE gp.id=$1',[req.params.id]);if(!q.rowCount)return res.status(404).json({success:false,message:'Gate pass not found'});res.json({success:true,gate_pass:q.rows[0]});}));
router.post('/',auth,roles,blockOffice001,asyncHandler(async(req,res)=>{const b=req.body||{};if(!b.student_id||!String(b.reason||'').trim()||!b.departure_at)return res.status(400).json({success:false,message:'Student, reason and departure are required'});const c=await pool.connect();try{await c.query('BEGIN');const existing=await c.query("SELECT id FROM student_gate_passes WHERE student_id=$1 AND status IN ('draft','pending')",[b.student_id]);if(existing.rowCount){await c.query('ROLLBACK');return res.status(409).json({success:false,message:'This student already has a ready or printed gate pass'});}const q=await c.query(`INSERT INTO student_gate_passes(student_id,reason,departure_at,expected_return_at,late_note,generated_by,status) VALUES($1,$2,$3,$4,$5,$6,'draft') RETURNING *`,[b.student_id,String(b.reason).trim(),b.departure_at,b.expected_return_at||null,b.late_note||null,req.user.userId]);const token='GP'+new Date().getFullYear()+String(q.rows[0].id).padStart(5,'0');await c.query('UPDATE student_gate_passes SET token_no=$1 WHERE id=$2',[token,q.rows[0].id]);await notifyGuardian(c,b.student_id,token,b.departure_at,req.user.userId);await c.query('COMMIT');res.status(201).json({success:true,id:q.rows[0].id,token_no:token,status:'draft'})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
router.post('/bulk',auth,roles,blockOffice001,asyncHandler(async(req,res)=>{const b=req.body||{};if(!b.class_name||!b.reason||!b.departure_at)return res.status(400).json({success:false,message:'Class, reason and departure are required'});const students=(await pool.query('SELECT id FROM students WHERE class_name=$1 AND is_active=TRUE',[b.class_name])).rows;let created=0,skipped=0;const c=await pool.connect();try{await c.query('BEGIN');for(const st of students){const old=await c.query("SELECT 1 FROM student_gate_passes WHERE student_id=$1 AND status IN ('draft','pending')",[st.id]);if(old.rowCount){skipped++;continue}const q=await c.query(`INSERT INTO student_gate_passes(student_id,reason,departure_at,expected_return_at,late_note,generated_by,status) VALUES($1,$2,$3,$4,$5,$6,'draft') RETURNING id`,[st.id,b.reason,b.departure_at,b.expected_return_at||null,b.late_note||null,req.user.userId]);const token='GP'+new Date().getFullYear()+String(q.rows[0].id).padStart(5,'0');await c.query('UPDATE student_gate_passes SET token_no=$1 WHERE id=$2',[token,q.rows[0].id]);await notifyGuardian(c,st.id,token,b.departure_at,req.user.userId);created++}await c.query('COMMIT');res.json({success:true,created,skipped})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
router.patch('/:id/print',auth,roles,asyncHandler(async(req,res)=>{const q=await pool.query("UPDATE student_gate_passes SET status='pending',printed_at=NOW(),printed_by=$1,updated_at=NOW() WHERE id=$2 AND status='draft' RETURNING *",[req.user.userId,req.params.id]);if(!q.rowCount)return res.status(409).json({success:false,message:'Only a ready-to-print gate pass can be printed'});res.json({success:true,gate_pass:q.rows[0]});}));
router.patch('/:id/execute',auth,roles,asyncHandler(async(req,res)=>{const q=await pool.query("UPDATE student_gate_passes SET status='returned',returned_at=COALESCE($1,NOW()),executed_by=$2,updated_at=NOW() WHERE id=$3 AND status='pending' RETURNING *",[req.body?.returned_at||null,req.user.userId,req.params.id]);if(!q.rowCount)return res.status(409).json({success:false,message:'Printed pending gate pass not found'});res.json({success:true,gate_pass:q.rows[0]});}));
router.patch('/:id/cancel',auth,roles,asyncHandler(async(req,res)=>{const q=await pool.query("UPDATE student_gate_passes SET status='cancelled',cancelled_at=NOW(),updated_at=NOW() WHERE id=$1 AND status IN ('draft','pending') RETURNING *",[req.params.id]);if(!q.rowCount)return res.status(409).json({success:false,message:'Active gate pass not found'});res.json({success:true});}));
module.exports=router;