const express=require('express');const pool=require('../db');const {auth,allow}=require('../middleware/auth');const asyncHandler=require('../utils/asyncHandler');const router=express.Router();
router.get('/exams',auth,asyncHandler(async(req,res)=>{const r=await pool.query(`SELECT * FROM exams ORDER BY created_at DESC`);res.json({success:true,exams:r.rows});}));
router.post('/exams',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const b=req.body;const r=await pool.query(`INSERT INTO exams(exam_name,class_name,session_name,exam_date,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[b.exam_name,b.class_name,b.session_name||null,b.exam_date||null,req.user.userId]);res.status(201).json({success:true,exam:r.rows[0]});}));
router.post('/subjects',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const r=await pool.query(`INSERT INTO subjects(subject_name) VALUES($1) ON CONFLICT(subject_name) DO UPDATE SET subject_name=EXCLUDED.subject_name RETURNING *`,[req.body.subject_name]);res.json({success:true,subject:r.rows[0]});}));
router.get('/subjects',auth,asyncHandler(async(req,res)=>{const r=await pool.query(`SELECT * FROM subjects WHERE is_active=TRUE ORDER BY subject_name`);res.json({success:true,subjects:r.rows});}));
router.post('/entry',auth,allow('super_admin','admin','teacher'),asyncHandler(async(req,res)=>{const b=req.body;const status=req.user.role==='teacher'?'pending':(b.verification_status||'pending');const r=await pool.query(`INSERT INTO student_marks(exam_id,student_id,subject_id,obtained_marks,grade,remarks,entered_by,verification_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
  ON CONFLICT(exam_id,student_id,subject_id) DO UPDATE SET obtained_marks=EXCLUDED.obtained_marks,grade=EXCLUDED.grade,remarks=EXCLUDED.remarks,entered_by=EXCLUDED.entered_by,verification_status=EXCLUDED.verification_status,verified_by=NULL,verified_at=NULL,updated_at=NOW() RETURNING *`,
  [b.exam_id,b.student_id,b.subject_id,b.obtained_marks,b.grade||null,b.remarks||null,req.user.userId,status]);res.json({success:true,mark:r.rows[0]});}));
router.get('/pending',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const r=await pool.query(`SELECT sm.*,e.exam_name,s.student_name,s.class_name,su.subject_name,u.full_name entered_by_name FROM student_marks sm JOIN exams e ON e.id=sm.exam_id JOIN students s ON s.id=sm.student_id JOIN subjects su ON su.id=sm.subject_id LEFT JOIN users u ON u.id=sm.entered_by WHERE sm.verification_status='pending' ORDER BY e.exam_name,s.class_name,s.student_name,su.subject_name`);res.json({success:true,marks:r.rows});}));
router.patch('/:id/verify',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const status=req.body.status==='rejected'?'rejected':'verified';const r=await pool.query(`UPDATE student_marks SET verification_status=$1,verified_by=$2,verified_at=CASE WHEN $1='verified' THEN NOW() ELSE NULL END,updated_at=NOW() WHERE id=$3 RETURNING *`,[status,req.user.userId,req.params.id]);res.json({success:true,mark:r.rows[0]});}));
router.patch('/exams/:id/publish',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const r=await pool.query(`UPDATE exams SET is_published=$1 WHERE id=$2 RETURNING *`,[!!req.body.is_published,req.params.id]);res.json({success:true,exam:r.rows[0]});}));
router.get('/exam/:examId/class/:className',auth,asyncHandler(async(req,res)=>{const r=await pool.query(`SELECT s.id student_id,s.registration_no,s.student_name,s.roll_no,s.class_name,su.subject_name,sm.obtained_marks,sm.grade,sm.verification_status FROM students s LEFT JOIN student_marks sm ON sm.student_id=s.id AND sm.exam_id=$1 LEFT JOIN subjects su ON su.id=sm.subject_id WHERE s.class_name=$2 ORDER BY s.roll_no,s.student_name,su.subject_name`,[req.params.examId,req.params.className]);res.json({success:true,rows:r.rows});}));
module.exports=router;
