const express=require('express');const pool=require('../db');const {auth,allow}=require('../middleware/auth');const asyncHandler=require('../utils/asyncHandler');const router=express.Router();
router.get('/',auth,asyncHandler(async(req,res)=>{const r=await pool.query(`SELECT * FROM routines WHERE is_active=TRUE ORDER BY published_at DESC`);res.json({success:true,routines:r.rows});}));
router.post('/',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const b=req.body;const r=await pool.query(`INSERT INTO routines(title,routine_date,routine_text,file_url,published_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[b.title||null,b.routine_date||null,b.routine_text||null,b.file_url||null,req.user.userId]);res.status(201).json({success:true,routine:r.rows[0]});}));

router.get('/manager',auth,asyncHandler(async(req,res)=>{const group=String(req.query.group||'v_x'),date=String(req.query.date||new Date().toISOString().slice(0,10));const r=await pool.query(`SELECT g.*,u.full_name updated_by_name FROM routine_manager_grids g LEFT JOIN users u ON u.id=g.created_by WHERE g.group_name=$1 AND (g.routine_date=$2 OR g.is_master=TRUE) ORDER BY (g.routine_date=$2) DESC,g.updated_at DESC LIMIT 1`,[group,date]);res.json({success:true,routine:r.rows[0]||null});}));
router.get('/manager/history',auth,asyncHandler(async(req,res)=>{const r=await pool.query(`SELECT id,group_name,routine_date,routine_kind,is_master,is_published,updated_at FROM routine_manager_grids WHERE group_name=$1 ORDER BY routine_date DESC,updated_at DESC LIMIT 60`,[String(req.query.group||'v_x')]);res.json({success:true,routines:r.rows});}));
router.post('/manager',auth,allow('super_admin','admin'),asyncHandler(async(req,res)=>{const b=req.body||{};if(!['v_x','xi_xii','coaching'].includes(b.group_name)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(String(b.routine_date||'')))return res.status(400).json({success:false,message:'Valid group and date are required'});const r=await pool.query(`INSERT INTO routine_manager_grids(group_name,routine_date,routine_kind,grid_data,is_master,is_published,created_by) VALUES($1,$2,$3,$4::jsonb,$5,TRUE,$6) ON CONFLICT(group_name,routine_date,routine_kind) DO UPDATE SET grid_data=EXCLUDED.grid_data,is_master=EXCLUDED.is_master,is_published=TRUE,created_by=EXCLUDED.created_by,updated_at=NOW() RETURNING *`,[b.group_name,b.routine_date,b.routine_kind||'daily',JSON.stringify(b.grid_data||{}),!!b.is_master,req.user.userId]);if(b.is_master)await pool.query(`UPDATE routine_manager_grids SET is_master=FALSE WHERE group_name=$1 AND id<>$2`,[b.group_name,r.rows[0].id]);res.json({success:true,routine:r.rows[0]});}));

module.exports=router;
