const express=require('express'),bcrypt=require('bcryptjs'),pool=require('../db');
const{auth,allow}=require('../middleware/auth');const asyncHandler=require('../utils/asyncHandler');const router=express.Router();
const schemaReady=pool.query(`
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN('super_admin','admin','teacher','guardian','gateman','office','library'));
CREATE TABLE IF NOT EXISTS service_staff_profiles(id BIGSERIAL PRIMARY KEY,user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,staff_id VARCHAR(100) UNIQUE NOT NULL,name VARCHAR(150) NOT NULL,staff_role VARCHAR(30) NOT NULL CHECK(staff_role IN('gateman','office','library')),mobile VARCHAR(30),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS gate_entry_logs(id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,permission_type VARCHAR(20) NOT NULL CHECK(permission_type IN('visit','gate_pass')),permission_id BIGINT NOT NULL,entered_by BIGINT REFERENCES users(id) ON DELETE SET NULL,entered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),remarks TEXT);
CREATE TABLE IF NOT EXISTS gate_guardian_visit_entries(id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,visitor_name VARCHAR(180) NOT NULL,visitor_relation VARCHAR(100) NOT NULL,visitor_source VARCHAR(30) NOT NULL CHECK(visitor_source IN('father','mother','visitor1','visitor2')),entered_by BIGINT REFERENCES users(id) ON DELETE SET NULL,entered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),remarks TEXT);
CREATE INDEX IF NOT EXISTS idx_gate_guardian_visits_student_time ON gate_guardian_visit_entries(student_id,entered_at DESC);
CREATE TABLE IF NOT EXISTS dining_stock(id BIGSERIAL PRIMARY KEY,item_name VARCHAR(150) UNIQUE NOT NULL,unit VARCHAR(30) NOT NULL,current_quantity NUMERIC(12,2) NOT NULL DEFAULT 0,reorder_level NUMERIC(12,2) NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS dining_stock_transactions(id BIGSERIAL PRIMARY KEY,stock_id BIGINT NOT NULL REFERENCES dining_stock(id) ON DELETE CASCADE,transaction_type VARCHAR(10) NOT NULL CHECK(transaction_type IN('in','out')),quantity NUMERIC(12,2) NOT NULL CHECK(quantity>0),note TEXT,entered_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE dining_stock_transactions ADD COLUMN IF NOT EXISTS transaction_date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE dining_stock_transactions ADD COLUMN IF NOT EXISTS invoice_no VARCHAR(100);
ALTER TABLE dining_stock_transactions ADD COLUMN IF NOT EXISTS supplier_name VARCHAR(180);
ALTER TABLE dining_stock_transactions ADD COLUMN IF NOT EXISTS rate NUMERIC(12,2);
ALTER TABLE dining_stock_transactions ADD COLUMN IF NOT EXISTS opening_quantity NUMERIC(12,2);
ALTER TABLE dining_stock_transactions ADD COLUMN IF NOT EXISTS closing_quantity NUMERIC(12,2);
CREATE TABLE IF NOT EXISTS library_books(id BIGSERIAL PRIMARY KEY,accession_no VARCHAR(100) UNIQUE NOT NULL,title VARCHAR(250) NOT NULL,author VARCHAR(180),total_copies INTEGER NOT NULL DEFAULT 1 CHECK(total_copies>=0),available_copies INTEGER NOT NULL DEFAULT 1 CHECK(available_copies>=0),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS book_number VARCHAR(50);
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS book_class VARCHAR(100);
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS part VARCHAR(50);
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS publisher VARCHAR(180);
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS publish_year INTEGER;
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS price NUMERIC(12,2);
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS purchase_date DATE;
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS rack_no VARCHAR(50);
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE library_books ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
CREATE TABLE IF NOT EXISTS library_loans(id BIGSERIAL PRIMARY KEY,book_id BIGINT NOT NULL REFERENCES library_books(id),student_id BIGINT NOT NULL REFERENCES students(id),issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),due_date DATE NOT NULL,returned_at TIMESTAMPTZ,issued_by BIGINT REFERENCES users(id) ON DELETE SET NULL,returned_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
DO $$ BEGIN IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='library_loans' AND column_name='issued_at' AND data_type='date') THEN ALTER TABLE library_loans ALTER COLUMN issued_at DROP DEFAULT; ALTER TABLE library_loans ALTER COLUMN issued_at TYPE TIMESTAMPTZ USING issued_at::timestamp AT TIME ZONE 'Asia/Kolkata'; ALTER TABLE library_loans ALTER COLUMN issued_at SET DEFAULT NOW(); END IF; END $$;
`);
const admin=allow('super_admin','admin');
router.get('/staff',auth,admin,asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`SELECT p.*,u.login_id,u.is_active FROM service_staff_profiles p JOIN users u ON u.id=p.user_id ORDER BY p.staff_role,p.name`);res.json({success:true,staff:q.rows})}));
router.post('/staff',auth,admin,asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{},role=String(b.role||'');if(!['gateman','office','library'].includes(role)||!b.staff_id||!b.name||!b.login_id||!b.password||b.password!==b.confirm_password)return res.status(400).json({success:false,message:'Role, staff ID, name, user ID, password and matching confirmation are required'});const c=await pool.connect();try{await c.query('BEGIN');const u=(await c.query(`INSERT INTO users(login_id,password_hash,full_name,role) VALUES($1,$2,$3,$4) RETURNING id`,[String(b.login_id).trim().toLowerCase(),await bcrypt.hash(String(b.password),12),String(b.name).trim(),role])).rows[0];const p=(await c.query(`INSERT INTO service_staff_profiles(user_id,staff_id,name,staff_role,mobile) VALUES($1,$2,$3,$4,$5) RETURNING *`,[u.id,String(b.staff_id).trim(),String(b.name).trim(),role,b.mobile||null])).rows[0];await c.query('COMMIT');res.status(201).json({success:true,staff:p})}catch(e){await c.query('ROLLBACK');if(e.code==='23505')return res.status(409).json({success:false,message:'User ID or Staff ID already exists'});throw e}finally{c.release()}}));
router.patch('/staff/:id',auth,admin,asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{};if(b.password&&b.password!==b.confirm_password)return res.status(400).json({success:false,message:'Password confirmation does not match'});const p=(await pool.query('SELECT * FROM service_staff_profiles WHERE id=$1',[req.params.id])).rows[0];if(!p)return res.status(404).json({success:false,message:'Staff not found'});await pool.query('UPDATE users SET is_active=COALESCE($1,is_active),password_hash=CASE WHEN $2::text IS NULL THEN password_hash ELSE $2 END WHERE id=$3',[b.is_active, b.password?await bcrypt.hash(String(b.password),12):null,p.user_id]);res.json({success:true})}));
router.get('/gate-today',auth,allow('gateman','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`
SELECT 'visit' permission_type,v.id permission_id,v.token_no,s.id student_id,s.registration_no,s.student_name,s.class_name,s.photo_url,r.room_name,v.visitor_name detail_name,v.visitor_relation detail_relation,v.visit_at permission_at,v.duration_minutes,NULL::text reason,EXISTS(SELECT 1 FROM gate_entry_logs gl WHERE gl.permission_type='visit' AND gl.permission_id=v.id AND gl.entered_at::date=CURRENT_DATE) entered
FROM student_visits v JOIN students s ON s.id=v.student_id LEFT JOIN rooms r ON r.id=s.room_id
WHERE v.visit_at::date=CURRENT_DATE AND v.status='approved' AND s.is_active=TRUE
UNION ALL
SELECT 'gate_pass',g.id,g.token_no,s.id,s.registration_no,s.student_name,s.class_name,s.photo_url,r.room_name,NULL,NULL,g.departure_at,NULL,g.reason,EXISTS(SELECT 1 FROM gate_entry_logs gl WHERE gl.permission_type='gate_pass' AND gl.permission_id=g.id AND gl.entered_at::date=CURRENT_DATE)
FROM student_gate_passes g JOIN students s ON s.id=g.student_id LEFT JOIN rooms r ON r.id=s.room_id
WHERE g.departure_at::date=CURRENT_DATE AND g.status IN('draft','pending') AND s.is_active=TRUE
ORDER BY permission_at,student_name`);res.json({success:true,date:new Date().toISOString().slice(0,10),permissions:q.rows})}));
router.get('/gate-check/:registration',auth,allow('gateman','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const st=(await pool.query(`SELECT s.id,s.registration_no,s.student_name,s.class_name,s.photo_url,s.father_name,s.mother_name,s.guardian_name,s.address,r.room_name FROM students s LEFT JOIN rooms r ON r.id=s.room_id WHERE s.registration_no=$1 AND s.is_active=TRUE`,[req.params.registration])).rows[0];if(!st)return res.status(404).json({success:false,message:'Active student not found'});const [visits,passes,visitors,docs,entries,guardians,meetingHistory,meetingCounts]=await Promise.all([pool.query(`SELECT id,token_no,visitor_name,visitor_relation,visit_at,duration_minutes,purpose,status FROM student_visits WHERE student_id=$1 AND visit_at::date=CURRENT_DATE AND status='approved' ORDER BY visit_at`,[st.id]),pool.query(`SELECT id,token_no,reason,departure_at,expected_return_at,status FROM student_gate_passes WHERE student_id=$1 AND departure_at::date=CURRENT_DATE AND status IN('draft','pending') ORDER BY departure_at`,[st.id]),pool.query(`SELECT visitor_number,visitor_name,relation FROM student_visitors WHERE student_id=$1 ORDER BY visitor_number`,[st.id]),pool.query(`SELECT document_type,file_url FROM student_documents WHERE student_id=$1 AND document_type IN('father_photo','mother_photo','visitor1_photo','visitor2_photo') ORDER BY uploaded_at DESC`,[st.id]),pool.query(`SELECT id,permission_type,permission_id,entered_at,remarks FROM gate_entry_logs WHERE student_id=$1 AND entered_at::date=CURRENT_DATE ORDER BY entered_at DESC`,[st.id]),pool.query(`SELECT gp.guardian_name,gp.address,gp.photo_url,sg.relation_type,sg.is_primary FROM student_guardians sg JOIN guardian_profiles gp ON gp.id=sg.guardian_id WHERE sg.student_id=$1 AND gp.is_active=TRUE ORDER BY sg.is_primary DESC,gp.guardian_name`,[st.id]),pool.query(`SELECT e.id,e.visitor_name,e.visitor_relation,e.visitor_source,e.entered_at,e.remarks,u.full_name entered_by_name FROM gate_guardian_visit_entries e LEFT JOIN users u ON u.id=e.entered_by WHERE e.student_id=$1 ORDER BY e.entered_at DESC LIMIT 100`,[st.id]),pool.query(`SELECT visitor_source,visitor_name,visitor_relation,COUNT(*)::int visit_count,MAX(entered_at) last_visit_at FROM gate_guardian_visit_entries WHERE student_id=$1 GROUP BY visitor_source,visitor_name,visitor_relation ORDER BY visitor_source`,[st.id])]);res.json({success:true,student:st,guardians:guardians.rows,visitors:visitors.rows,photos:Object.fromEntries(docs.rows.map(x=>[x.document_type,x.file_url])),visits:visits.rows,gate_passes:passes.rows,entries:entries.rows,meeting_history:meetingHistory.rows,meeting_counts:meetingCounts.rows,meeting_total:meetingCounts.rows.reduce((sum,row)=>sum+Number(row.visit_count),0)})}));
router.post('/guardian-entry',auth,allow('gateman','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const studentId=Number(req.body?.student_id),source=String(req.body?.visitor_source||'').trim().toLowerCase();if(!studentId||!['father','mother','visitor1','visitor2'].includes(source))return res.status(400).json({success:false,message:'Student and visitor card are required'});const student=(await pool.query('SELECT id,father_name,mother_name FROM students WHERE id=$1 AND is_active=TRUE',[studentId])).rows[0];if(!student)return res.status(404).json({success:false,message:'Active student not found'});let name='',relation='';if(source==='father'){name=student.father_name;relation='Father'}else if(source==='mother'){name=student.mother_name;relation='Mother'}else{const number=Number(source.replace('visitor',''));const visitor=(await pool.query('SELECT visitor_name,relation FROM student_visitors WHERE student_id=$1 AND visitor_number=$2',[studentId,number])).rows[0];name=visitor?.visitor_name;relation=visitor?.relation||('Visitor '+number)}if(!String(name||'').trim())return res.status(409).json({success:false,message:'This visitor is not recorded for the student'});const entry=(await pool.query(`INSERT INTO gate_guardian_visit_entries(student_id,visitor_name,visitor_relation,visitor_source,entered_by,remarks) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[studentId,String(name).trim(),String(relation).trim(),source,req.user.userId,req.body?.remarks||null])).rows[0];const total=(await pool.query('SELECT COUNT(*)::int count FROM gate_guardian_visit_entries WHERE student_id=$1',[studentId])).rows[0].count;res.status(201).json({success:true,message:'Guardian meeting entry recorded',entry,total})}));
router.post('/gate-entry',auth,allow('gateman','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{},type=b.permission_type;if(!['visit','gate_pass'].includes(type)||!b.permission_id)return res.status(400).json({success:false,message:'Choose a valid permission'});const table=type==='visit'?'student_visits':'student_gate_passes',dateCol=type==='visit'?'visit_at':'departure_at';const statusCondition=type==='visit'?"status='approved'":"status IN('draft','pending')";const q=await pool.query(`SELECT student_id FROM ${table} WHERE id=$1 AND ${dateCol}::date=CURRENT_DATE AND ${statusCondition}`,[b.permission_id]);if(!q.rowCount)return res.status(409).json({success:false,message:'Today’s valid permission was not found'});if((await pool.query('SELECT 1 FROM gate_entry_logs WHERE permission_type=$1 AND permission_id=$2 AND entered_at::date=CURRENT_DATE',[type,b.permission_id])).rowCount)return res.status(409).json({success:false,message:'This permission has already been entered today'});const log=(await pool.query(`INSERT INTO gate_entry_logs(student_id,permission_type,permission_id,entered_by,remarks) VALUES($1,$2,$3,$4,$5) RETURNING *`,[q.rows[0].student_id,type,b.permission_id,req.user.userId,b.remarks||null])).rows[0];res.status(201).json({success:true,entry:log})}));
router.get('/dining',auth,allow('office','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query('SELECT * FROM dining_stock ORDER BY item_name');res.json({success:true,stock:q.rows})}));
router.get('/dining/transactions',auth,allow('office','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`SELECT t.*,s.item_name,s.unit,u.full_name entered_by_name FROM dining_stock_transactions t JOIN dining_stock s ON s.id=t.stock_id LEFT JOIN users u ON u.id=t.entered_by ORDER BY t.created_at DESC,t.id DESC LIMIT 500`);res.json({success:true,transactions:q.rows})}));
router.post('/dining/items',auth,allow('office','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{};if(!b.item_name||!b.unit)return res.status(400).json({success:false,message:'Item and unit are required'});const q=await pool.query(`INSERT INTO dining_stock(item_name,unit,current_quantity,reorder_level) VALUES($1,$2,$3,$4) RETURNING *`,[b.item_name,b.unit,Number(b.current_quantity)||0,Number(b.reorder_level)||0]);res.status(201).json({success:true,item:q.rows[0]})}));
router.post('/dining/transaction',auth,allow('office','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{},qty=Number(b.quantity);if(!b.stock_id||!['in','out'].includes(b.transaction_type)||!(qty>0))return res.status(400).json({success:false,message:'Stock item, type and positive quantity are required'});const c=await pool.connect();try{await c.query('BEGIN');const st=(await c.query('SELECT * FROM dining_stock WHERE id=$1 FOR UPDATE',[b.stock_id])).rows[0];if(!st)throw new Error('Stock item not found');const transactionDate=b.transaction_date||null;const duplicate=await c.query(`SELECT id FROM dining_stock_transactions WHERE stock_id=$1 AND transaction_type=$2 AND transaction_date=COALESCE($3::date,CURRENT_DATE) LIMIT 1`,[st.id,b.transaction_type,transactionDate]);if(duplicate.rowCount)throw new Error(st.item_name+' already has a Stock '+(b.transaction_type==='in'?'In':'Out')+' entry for this date');const next=Number(st.current_quantity)+(b.transaction_type==='in'?qty:-qty);if(next<0)throw new Error('Quantity Out cannot exceed available balance of '+Number(st.current_quantity)+' '+st.unit);await c.query('UPDATE dining_stock SET current_quantity=$1,updated_at=NOW() WHERE id=$2',[next,st.id]);await c.query(`INSERT INTO dining_stock_transactions(stock_id,transaction_type,quantity,note,entered_by,transaction_date,invoice_no,supplier_name,rate,opening_quantity,closing_quantity) VALUES($1,$2,$3,$4,$5,COALESCE($6::date,CURRENT_DATE),$7,$8,$9,$10,$11)`,[st.id,b.transaction_type,qty,b.note||null,req.user.userId,b.transaction_date||null,b.invoice_no||null,b.supplier_name||null,b.rate===''||b.rate==null?null:Number(b.rate),Number(st.current_quantity),next]);await c.query('COMMIT');res.json({success:true,current_quantity:next})}catch(e){await c.query('ROLLBACK');res.status(409).json({success:false,message:e.message})}finally{c.release()}}));
router.get('/library/status',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const status=String(req.query.status||'issued'),search='%'+String(req.query.q||'').trim()+'%';if(status==='issued'){const q=await pool.query(`SELECT l.id loan_id,l.issued_at,l.due_date,b.id book_id,b.accession_no,b.title,b.author,s.id student_id,s.registration_no,s.student_name,s.class_name FROM library_loans l JOIN library_books b ON b.id=l.book_id JOIN students s ON s.id=l.student_id WHERE l.returned_at IS NULL AND ($1='%%' OR b.title ILIKE $1 OR b.accession_no ILIKE $1 OR s.student_name ILIKE $1 OR s.registration_no ILIKE $1) ORDER BY l.issued_at DESC`,[search]);return res.json({success:true,status,records:q.rows})}const q=await pool.query(`SELECT b.*,GREATEST(b.available_copies,0)::int available_count FROM library_books b WHERE b.is_active=TRUE AND b.available_copies>0 AND ($1='%%' OR b.title ILIKE $1 OR b.accession_no ILIKE $1 OR COALESCE(b.author,'') ILIKE $1) ORDER BY b.title,b.accession_no`,[search]);res.json({success:true,status:'available',records:q.rows})}));router.get('/library/books',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`SELECT b.*,(SELECT COUNT(*) FROM library_loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) issued_count FROM library_books b WHERE b.is_active=TRUE AND ($1='' OR b.title ILIKE $2 OR b.accession_no ILIKE $2) AND ($3='' OR b.category=$3) AND ($4='' OR b.book_class=$4) ORDER BY b.title`,[String(req.query.q||''),'%'+String(req.query.q||'')+'%',String(req.query.category||''),String(req.query.book_class||'')]);res.json({success:true,books:q.rows})}));
router.post('/library/books',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{},copies=Math.max(1,Number(b.total_copies)||1);if(!b.accession_no||!b.title)return res.status(400).json({success:false,message:'Accession number and title are required'});const q=await pool.query(`INSERT INTO library_books(accession_no,title,author,total_copies,available_copies,book_class,part,category,publisher,publish_year,price,purchase_date,rack_no,book_number) VALUES($1,$2,$3,$4,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[b.accession_no,b.title,b.author||null,copies,b.book_class||null,b.part||null,b.category||null,b.publisher||null,b.publish_year?Number(b.publish_year):null,b.price?Number(b.price):null,b.purchase_date||null,b.rack_no||null,b.book_number||null]);res.status(201).json({success:true,book:q.rows[0]})}));
router.patch('/library/books/:id',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{},copies=Math.max(1,Number(b.total_copies)||1),current=(await pool.query('SELECT * FROM library_books WHERE id=$1 AND is_active=TRUE',[req.params.id])).rows[0];if(!current)return res.status(404).json({success:false,message:'Book not found'});const issued=Number(current.total_copies)-Number(current.available_copies);if(copies<issued)return res.status(409).json({success:false,message:`Total copies cannot be less than ${issued} currently issued copies`});const q=await pool.query(`UPDATE library_books SET accession_no=$1,title=$2,author=$3,total_copies=$4,available_copies=$4-$5,book_class=$6,part=$7,category=$8,publisher=$9,publish_year=$10,price=$11,purchase_date=$12,rack_no=$13,book_number=$14,updated_at=NOW() WHERE id=$15 RETURNING *`,[b.accession_no,b.title,b.author||null,copies,issued,b.book_class||null,b.part||null,b.category||null,b.publisher||null,b.publish_year?Number(b.publish_year):null,b.price?Number(b.price):null,b.purchase_date||null,b.rack_no||null,b.book_number||null,req.params.id]);res.json({success:true,book:q.rows[0]})}));
router.patch('/library/books/:id/archive',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;if((await pool.query('SELECT 1 FROM library_loans WHERE book_id=$1 AND returned_at IS NULL',[req.params.id])).rowCount)return res.status(409).json({success:false,message:'Return all issued copies before archiving this book'});const q=await pool.query('UPDATE library_books SET is_active=FALSE,updated_at=NOW() WHERE id=$1 AND is_active=TRUE RETURNING id',[req.params.id]);if(!q.rowCount)return res.status(404).json({success:false,message:'Active book not found'});res.json({success:true})}));router.get('/library/book/:barcode',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const code=String(req.params.barcode||'').trim();const book=(await pool.query(`SELECT b.*,(SELECT COUNT(*) FROM library_loans l WHERE l.book_id=b.id AND l.returned_at IS NULL) issued_count FROM library_books b WHERE b.is_active=TRUE AND (lower(b.accession_no)=lower($1) OR lower(COALESCE(b.book_number,''))=lower($1)) LIMIT 1`,[code])).rows[0];if(!book)return res.status(404).json({success:false,message:'Book Number / Barcode not found'});if(Number(book.available_copies)<1)return res.status(409).json({success:false,message:'This book is currently issued / unavailable',book});res.json({success:true,book})}));router.get('/library/student/:registration',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const st=(await pool.query('SELECT id,registration_no,student_name,class_name,photo_url FROM students WHERE registration_no=$1 AND is_active=TRUE',[req.params.registration])).rows[0];if(!st)return res.status(404).json({success:false,message:'Active student not found'});const loans=(await pool.query(`SELECT l.*,b.accession_no,b.title,b.author FROM library_loans l JOIN library_books b ON b.id=l.book_id WHERE l.student_id=$1 ORDER BY l.returned_at NULLS FIRST,l.issued_at DESC`,[st.id])).rows;res.json({success:true,student:st,loans})}));
router.post('/library/issue',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{};if(!b.book_id||!b.student_id||!b.due_date)return res.status(400).json({success:false,message:'Book, student and due date are required'});const c=await pool.connect();try{await c.query('BEGIN');const book=(await c.query('SELECT * FROM library_books WHERE id=$1 FOR UPDATE',[b.book_id])).rows[0];if(!book||book.available_copies<1)throw new Error('Book is not available');await c.query(`INSERT INTO library_loans(book_id,student_id,due_date,issued_by) VALUES($1,$2,$3,$4)`,[book.id,b.student_id,b.due_date,req.user.userId]);await c.query('UPDATE library_books SET available_copies=available_copies-1 WHERE id=$1',[book.id]);await c.query('COMMIT');res.status(201).json({success:true})}catch(e){await c.query('ROLLBACK');res.status(409).json({success:false,message:e.message})}finally{c.release()}}));
router.patch('/library/loans/:id/return',auth,allow('library','super_admin','admin'),asyncHandler(async(req,res)=>{await schemaReady;const c=await pool.connect();try{await c.query('BEGIN');const loan=(await c.query('UPDATE library_loans SET returned_at=NOW(),returned_by=$1 WHERE id=$2 AND returned_at IS NULL RETURNING *',[req.user.userId,req.params.id])).rows[0];if(!loan)throw new Error('Active loan not found');await c.query('UPDATE library_books SET available_copies=available_copies+1 WHERE id=$1',[loan.book_id]);await c.query('COMMIT');res.json({success:true})}catch(e){await c.query('ROLLBACK');res.status(409).json({success:false,message:e.message})}finally{c.release()}}));
module.exports=router;
