const express=require('express');
const pool=require('../db');
const {auth,allow}=require('../middleware/auth');
const asyncHandler=require('../utils/asyncHandler');
const router=express.Router();
const roles=allow('super_admin','admin');
const schemaReady=pool.query(`CREATE TABLE IF NOT EXISTS student_visits(
 id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
 token_no VARCHAR(40) UNIQUE,visitor_name VARCHAR(150) NOT NULL,visitor_relation VARCHAR(100) NOT NULL,
 visit_at TIMESTAMPTZ NOT NULL,duration_minutes INTEGER NOT NULL DEFAULT 15,
 purpose TEXT,status VARCHAR(20) NOT NULL DEFAULT 'approved' CHECK(status IN ('approved','completed','cancelled')),
 approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,completed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
 completed_at TIMESTAMPTZ,cancelled_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`);
const fields=`SELECT v.*,to_char(v.visit_at,'YYYY-MM-DD HH24:MI') visit_text,s.registration_no,s.student_name,s.class_name,s.photo_url,s.guardian_name,s.father_name,s.guardian_mobile,s.whatsapp_number,r.room_name,u.full_name approved_by_name FROM student_visits v JOIN students s ON s.id=v.student_id LEFT JOIN rooms r ON r.id=s.room_id LEFT JOIN users u ON u.id=v.approved_by`;
const digits=v=>String(v||'').replace(/\D/g,'');
const whatsapp=(student,visit)=>{let phone=digits(student.whatsapp_number||student.guardian_mobile);if(phone.length===10)phone='91'+phone;const when=new Date(visit.visit_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'});const message=`Al-Ameen Mission Academy Memari\n\nVisit permission approved for ${student.student_name} (Reg. ${student.registration_no}, Class ${student.class_name||'-'}).\nVisitor: ${visit.visitor_name} (${visit.visitor_relation})\nDate & Time: ${when}\nDuration: ${visit.duration_minutes} minutes\nToken: ${visit.token_no}\n\nPlease follow the approved schedule.`;return phone?`https://wa.me/${phone}?text=${encodeURIComponent(message)}`:''};
router.get('/student/:registration',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`SELECT s.id,s.registration_no,s.student_name,s.class_name,s.photo_url,s.guardian_name,s.father_name,s.guardian_mobile,s.whatsapp_number,r.room_name FROM students s LEFT JOIN rooms r ON r.id=s.room_id WHERE s.registration_no=$1 AND s.is_active=TRUE`,[req.params.registration]);if(!q.rowCount)return res.status(404).json({success:false,message:'Active student not found'});res.json({success:true,student:q.rows[0]})}));
router.get('/',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const args=[],where=[];if(req.query.year){args.push(String(req.query.year));where.push(`to_char(v.visit_at,'YYYY')=$${args.length}`)}if(req.query.class_name){args.push(String(req.query.class_name));where.push(`s.class_name=$${args.length}`)}if(req.query.status){args.push(String(req.query.status));where.push(`v.status=$${args.length}`)}if(req.query.q){args.push('%'+String(req.query.q)+'%');where.push(`(s.registration_no ILIKE $${args.length} OR s.student_name ILIKE $${args.length} OR v.visitor_name ILIKE $${args.length} OR v.token_no ILIKE $${args.length})`)}const q=await pool.query(fields+(where.length?' WHERE '+where.join(' AND '):'')+' ORDER BY v.visit_at DESC LIMIT 500',args);res.json({success:true,visits:q.rows})}));
router.post('/',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{};if(!b.student_id||!String(b.visitor_name||'').trim()||!String(b.visitor_relation||'').trim()||!b.visit_at)return res.status(400).json({success:false,message:'Student, visitor name, relation, date and time are required'});const c=await pool.connect();try{await c.query('BEGIN');const student=(await c.query('SELECT * FROM students WHERE id=$1 AND is_active=TRUE',[b.student_id])).rows[0];if(!student){await c.query('ROLLBACK');return res.status(404).json({success:false,message:'Active student not found'})}const visit=(await c.query(`INSERT INTO student_visits(student_id,visitor_name,visitor_relation,visit_at,duration_minutes,purpose,approved_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[b.student_id,String(b.visitor_name).trim(),String(b.visitor_relation).trim(),b.visit_at,Math.max(5,Number(b.duration_minutes)||15),String(b.purpose||'').trim()||null,req.user.userId])).rows[0];visit.token_no='VIS'+new Date().getFullYear()+String(visit.id).padStart(5,'0');await c.query('UPDATE student_visits SET token_no=$1 WHERE id=$2',[visit.token_no,visit.id]);const notice=(await c.query(`INSERT INTO notices(title,notice_text,notice_type,published_by,is_active,published_at) VALUES($1,$2,'visit',$3,TRUE,NOW()) RETURNING id`,['Visit Permission Approved',`Visit ${visit.token_no}: ${visit.visitor_name} (${visit.visitor_relation}) may meet ${student.student_name} on ${String(b.visit_at).replace('T',' ')} for ${visit.duration_minutes} minutes.`,req.user.userId])).rows[0];await c.query(`INSERT INTO notice_targets(notice_id,target_type,target_value) VALUES($1,'student',$2)`,[notice.id,String(student.id)]);await c.query('COMMIT');res.status(201).json({success:true,visit,whatsapp_url:whatsapp(student,visit)})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
router.patch('/:id/execute',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`UPDATE student_visits SET status='completed',completed_at=NOW(),completed_by=$1,updated_at=NOW() WHERE id=$2 AND status='approved' RETURNING *`,[req.user.userId,req.params.id]);if(!q.rowCount)return res.status(409).json({success:false,message:'Approved visit not found'});res.json({success:true,visit:q.rows[0]})}));
router.patch('/:id/cancel',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`UPDATE student_visits SET status='cancelled',cancelled_at=NOW(),updated_at=NOW() WHERE id=$1 AND status='approved' RETURNING *`,[req.params.id]);if(!q.rowCount)return res.status(409).json({success:false,message:'Approved visit not found'});res.json({success:true,visit:q.rows[0]})}));
module.exports=router;
