const express=require('express');
const pool=require('../db');
const {auth,allow}=require('../middleware/auth');
const asyncHandler=require('../utils/asyncHandler');
const router=express.Router(),roles=allow('super_admin','admin');
const schemaReady=pool.query(`CREATE TABLE IF NOT EXISTS student_visits(id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,token_no VARCHAR(40) UNIQUE,visitor_name VARCHAR(150) NOT NULL,visitor_relation VARCHAR(100) NOT NULL,visit_at TIMESTAMPTZ NOT NULL,duration_minutes INTEGER NOT NULL DEFAULT 15,purpose TEXT,status VARCHAR(20) NOT NULL DEFAULT 'approved' CHECK(status IN ('approved','completed','cancelled')),approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,completed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,completed_at TIMESTAMPTZ,cancelled_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
const visitorEntriesReady=pool.query(`CREATE TABLE IF NOT EXISTS gate_guardian_visit_entries(id BIGSERIAL PRIMARY KEY,student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,visitor_name VARCHAR(180) NOT NULL,visitor_relation VARCHAR(100) NOT NULL,visitor_source VARCHAR(30) NOT NULL,entered_by BIGINT REFERENCES users(id) ON DELETE SET NULL,entered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),remarks TEXT);ALTER TABLE gate_guardian_visit_entries ADD COLUMN IF NOT EXISTS permission_id BIGINT;ALTER TABLE gate_guardian_visit_entries ADD COLUMN IF NOT EXISTS entry_mode VARCHAR(30) NOT NULL DEFAULT 'without_permission';ALTER TABLE gate_guardian_visit_entries ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;`);
const fields=`SELECT v.*,to_char(v.visit_at,'YYYY-MM-DD HH24:MI') visit_text,s.registration_no,s.student_name,s.class_name,s.photo_url,s.guardian_name,s.father_name,s.guardian_mobile,s.whatsapp_number,r.room_name,u.full_name approved_by_name FROM student_visits v JOIN students s ON s.id=v.student_id LEFT JOIN rooms r ON r.id=s.room_id LEFT JOIN users u ON u.id=v.approved_by`;
const digits=v=>String(v||'').replace(/\D/g,'');
const validFuture=value=>{const d=new Date(value);return !Number.isNaN(d.getTime())&&d.getTime()>=Date.now()-60000};
const whatsapp=(student,visit)=>{let phone=digits(student.whatsapp_number||student.guardian_mobile);if(phone.length===10)phone='91'+phone;const when=new Date(visit.visit_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'});const message=`Al-Ameen Mission Academy Memari\n\nVisit permission approved for ${student.student_name} (Reg. ${student.registration_no}, Class ${student.class_name||'-'}).\nVisitor: ${visit.visitor_name} (${visit.visitor_relation})\nDate & Time: ${when}\nDuration: ${visit.duration_minutes} minutes\nToken: ${visit.token_no}\n\nPlease follow the approved schedule.`;return phone?`whatsapp://send?phone=${phone}&text=${encodeURIComponent(message)}`:''};
async function choices(db,student){const visitors=(await db.query(`SELECT visitor_name,relation,visitor_number FROM student_visitors WHERE student_id=$1 AND visitor_name IS NOT NULL ORDER BY visitor_number`,[student.id])).rows;return[{visitor_name:student.father_name,relation:'Father',source:'Father'},{visitor_name:student.mother_name,relation:'Mother',source:'Mother'},...visitors.map(v=>({...v,source:'Visitor '+v.visitor_number}))].filter(v=>String(v.visitor_name||'').trim())}
async function createVisit(c,student,b,userId){const visit=(await c.query(`INSERT INTO student_visits(student_id,visitor_name,visitor_relation,visit_at,duration_minutes,purpose,approved_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[student.id,String(b.visitor_name).trim(),String(b.visitor_relation).trim(),b.visit_at,Math.max(5,Number(b.duration_minutes)||15),String(b.purpose||'').trim()||null,userId])).rows[0];visit.token_no='VIS'+new Date().getFullYear()+String(visit.id).padStart(5,'0');await c.query('UPDATE student_visits SET token_no=$1 WHERE id=$2',[visit.token_no,visit.id]);const notice=(await c.query(`INSERT INTO notices(title,notice_text,notice_type,published_by,is_active,published_at) VALUES($1,$2,'visit',$3,TRUE,NOW()) RETURNING id`,['Visit Permission Approved',`Visit ${visit.token_no}: ${visit.visitor_name} (${visit.visitor_relation}) may meet ${student.student_name} on ${String(b.visit_at).replace('T',' ')} for ${visit.duration_minutes} minutes.`,userId])).rows[0];await c.query(`INSERT INTO notice_targets(notice_id,target_type,target_value) VALUES($1,'student',$2)`,[notice.id,String(student.id)]);return visit}
router.get('/student/:registration',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`SELECT s.*,r.room_name FROM students s LEFT JOIN rooms r ON r.id=s.room_id WHERE s.registration_no=$1 AND s.is_active=TRUE`,[req.params.registration]);if(!q.rowCount)return res.status(404).json({success:false,message:'Active student not found'});const student=q.rows[0];student.visitor_choices=await choices(pool,student);res.json({success:true,student})}));
router.get('/students/search',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const v=[],w=['s.is_active=TRUE'];if(req.query.class_name){v.push(String(req.query.class_name));w.push(`s.class_name=$${v.length}`)}if(req.query.q){v.push('%'+String(req.query.q)+'%');w.push(`(s.registration_no ILIKE $${v.length} OR s.student_name ILIKE $${v.length} OR s.father_name ILIKE $${v.length} OR s.mother_name ILIKE $${v.length})`)}const q=await pool.query(`SELECT s.id,s.registration_no,s.student_name,s.class_name,s.roll_no,s.father_name,s.mother_name,s.guardian_mobile,s.whatsapp_number,COALESCE(json_agg(json_build_object('visitor_name',sv.visitor_name,'relation',sv.relation,'visitor_number',sv.visitor_number) ORDER BY sv.visitor_number) FILTER(WHERE sv.id IS NOT NULL AND sv.visitor_name IS NOT NULL),'[]') visitors FROM students s LEFT JOIN student_visitors sv ON sv.student_id=s.id WHERE ${w.join(' AND ')} GROUP BY s.id ORDER BY s.class_name,s.roll_no,s.student_name LIMIT 300`,v);for(const student of q.rows){student.visitor_choices=[{visitor_name:student.father_name,relation:'Father',source:'Father'},{visitor_name:student.mother_name,relation:'Mother',source:'Mother'},...(student.visitors||[]).map(x=>({...x,source:'Visitor '+x.visitor_number}))].filter(x=>String(x.visitor_name||'').trim());delete student.visitors}res.json({success:true,students:q.rows})}));
router.get('/guardian-entries',auth,roles,asyncHandler(async(req,res)=>{await Promise.all([schemaReady,visitorEntriesReady]);const q=await pool.query(`SELECT e.*,s.registration_no,s.student_name,s.class_name,u.full_name entered_by_name FROM gate_guardian_visit_entries e JOIN students s ON s.id=e.student_id LEFT JOIN users u ON u.id=e.entered_by ORDER BY e.entered_at DESC LIMIT 500`);res.json({success:true,entries:q.rows})}));
router.patch('/guardian-entries/:id/activate',auth,roles,asyncHandler(async(req,res)=>{await visitorEntriesReady;const q=await pool.query(`UPDATE gate_guardian_visit_entries SET is_active=TRUE WHERE id=$1 RETURNING *`,[req.params.id]);if(!q.rowCount)return res.status(404).json({success:false,message:'Visitor entry not found'});res.json({success:true,entry:q.rows[0]})}));
router.get('/',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const a=[],w=[];if(req.query.year){a.push(String(req.query.year));w.push(`to_char(v.visit_at,'YYYY')=$${a.length}`)}if(req.query.class_name){a.push(String(req.query.class_name));w.push(`s.class_name=$${a.length}`)}if(req.query.status){a.push(String(req.query.status));w.push(`v.status=$${a.length}`)}if(req.query.q){a.push('%'+String(req.query.q)+'%');w.push(`(s.registration_no ILIKE $${a.length} OR s.student_name ILIKE $${a.length} OR v.visitor_name ILIKE $${a.length} OR v.token_no ILIKE $${a.length})`)}const q=await pool.query(fields+(w.length?' WHERE '+w.join(' AND '):'')+' ORDER BY v.visit_at DESC LIMIT 500',a);res.json({success:true,visits:q.rows})}));
router.post('/',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{};if(!b.student_id||!String(b.visitor_name||'').trim()||!String(b.visitor_relation||'').trim()||!b.visit_at)return res.status(400).json({success:false,message:'Student, visitor name, relation, date and time are required'});if(!validFuture(b.visit_at))return res.status(400).json({success:false,message:'Back-date visit permission is not allowed'});const c=await pool.connect();try{await c.query('BEGIN');const student=(await c.query('SELECT * FROM students WHERE id=$1 AND is_active=TRUE',[b.student_id])).rows[0];if(!student){await c.query('ROLLBACK');return res.status(404).json({success:false,message:'Active student not found'})}const visit=await createVisit(c,student,b,req.user.userId);await c.query('COMMIT');res.status(201).json({success:true,visit,whatsapp_url:whatsapp(student,visit)})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
router.post('/bulk',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const b=req.body||{},entries=Array.isArray(b.entries)?b.entries:[];if(!entries.length)return res.status(400).json({success:false,message:'Select at least one student'});if(!validFuture(b.visit_at))return res.status(400).json({success:false,message:'Back-date visit permission is not allowed'});const c=await pool.connect();try{await c.query('BEGIN');const out=[];for(const e of entries){const student=(await c.query('SELECT * FROM students WHERE id=$1 AND is_active=TRUE',[e.student_id])).rows[0];if(!student)throw new Error('One or more selected students are unavailable');const visitor=(e.visitor_name&&e.visitor_relation)?e:(await choices(c,student))[0];if(!visitor)throw new Error(`No visitor is recorded for ${student.student_name}`);const visit=await createVisit(c,student,{...b,...visitor},req.user.userId);out.push({visit,whatsapp_url:whatsapp(student,visit)})}await c.query('COMMIT');res.status(201).json({success:true,created:out.length,results:out})}catch(e){await c.query('ROLLBACK');res.status(409).json({success:false,message:e.message})}finally{c.release()}}));
router.patch('/:id/execute',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`UPDATE student_visits SET status='completed',completed_at=NOW(),completed_by=$1,updated_at=NOW() WHERE id=$2 AND status='approved' RETURNING *`,[req.user.userId,req.params.id]);if(!q.rowCount)return res.status(409).json({success:false,message:'Approved visit not found'});res.json({success:true,visit:q.rows[0]})}));
router.patch('/:id/cancel',auth,roles,asyncHandler(async(req,res)=>{await schemaReady;const q=await pool.query(`UPDATE student_visits SET status='cancelled',cancelled_at=NOW(),updated_at=NOW() WHERE id=$1 AND status='approved' RETURNING *`,[req.params.id]);if(!q.rowCount)return res.status(409).json({success:false,message:'Approved visit not found'});res.json({success:true,visit:q.rows[0]})}));
module.exports=router;
